// packages/react-lib/src/components/cards/BaseCard/BaseCard.tsx
import { ReactNode } from "react";
import { CardVariant } from "@m2s2/models";
import "./BaseCard.scss";

interface BaseCardProps {
  children: ReactNode;
  featured?: boolean;
  variant?: CardVariant;
}

export function BaseCard({
  children,
  featured = false,
  variant = "default",
}: BaseCardProps) {
  return (
    <article
      className={`m2s2-card${featured ? " featured" : ""}`}
      data-variant={variant}
    >
      {children}
    </article>
  );
}

// packages/ng-lib/src/lib/components/cards/base-card/base-card.component.ts
import { Component, input } from '@angular/core';
import { CardVariant } from '../../../models/card/card.model';

@Component({
  selector: 'm2s2-card',
  templateUrl: './base-card.component.html',
  styleUrls: ['./base-card.component.scss'],
  standalone: true,
  host: {
    'role': 'article',
    '[class.featured]': 'featured()',
    '[attr.data-variant]': 'variant()',
  },
})
export class BaseCardComponent {
  featured = input(false);
  variant  = input<CardVariant>('default');
}
