// packages/react-lib/src/components/PageHeader/PageHeader.tsx
import { PageHeaderConfig } from "@m2s2/models";
import "./PageHeader.scss";

interface PageHeaderProps {
  config: PageHeaderConfig;
}

export function PageHeader({ config }: PageHeaderProps) {
  return (
    <header className="m2s2-page-header">
      <h1 className="page-title">{config.title}</h1>
      <p className="page-subtitle">{config.subtitle}</p>
    </header>
  );
}

// packages/vue-lib/src/components/PageHeader/PageHeader.vue
<script setup lang="ts">
import type { PageHeaderConfig } from "@m2s2/models";

defineProps<{ config: PageHeaderConfig }>();
</script>

<template>
  <header class="m2s2-page-header">
    <h1 class="page-title">
      {{ config.title }}
    </h1>
    <p class="page-subtitle">
      {{ config.subtitle }}
    </p>
  </header>
</template>

<style lang="scss">
@use "packages/tokens/src/components/page-header";

.m2s2-page-header {
  display: block;
  text-align: center;
  margin-bottom: var(--space-12);
}
</style>
