// packages/ng-lib/src/lib/components/page-header/page-header.component.ts
import { Component, input } from '@angular/core';
import { PageHeaderConfig } from '../../models/page-header/page-header.model';

@Component({
  selector: 'm2s2-page-header',
  templateUrl: './page-header.component.html',
  styleUrls: ['./page-header.component.scss'],
  standalone: true,
})
export class PageHeaderComponent {
  config = input.required<PageHeaderConfig>();
}

<header class="m2s2-page-header">
  <h1 class="page-title">{{ config().title }}</h1>
  <p class="page-subtitle">{{ config().subtitle }}</p>
</header>

// packages/react-lib/src/components/PageHeader/PageHeader.tsx
import { PageHeaderConfig } from "@m2s2/models";
import "./PageHeader.scss";

interface PageHeaderProps {
  config: PageHeaderConfig;
}

export function PageHeader({ config }: PageHeaderProps) {
  return (
    <header className="m2s2-page-header">
      <h1 className="page-title">{config.title}</h1>
      <p className="page-subtitle">{config.subtitle}</p>
    </header>
  );
}
