// packages/vue-lib/src/components/BlogEditor/BlogEditor.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { marked } from "marked";
import type { BlogDraft, BlogPost } from "@m2s2/models";
import {
  BLOG_EDITOR_TOOLBAR,
  calcReadingTime,
  generateSlug,
  todayAsIsoDate,
} from "@m2s2/utils";
import type { ToolbarItem } from "@m2s2/utils";

const props = withDefaults(
  defineProps<{
    /** Populate fields when editing an existing post. */
    initialPost?: BlogPost;
    /** Set to the S3 URL after the platform has uploaded the selected cover image. */
    coverImageUrl?: string;
    /** Existing series to show in the dropdown. Platform fetches these from the blog index. */
    existingSeries?: Array<{ id: string; title: string }>;
  }>(),
  {
    initialPost: undefined,
    coverImageUrl: undefined,
    existingSeries: () => [],
  },
);

const emit = defineEmits<{
  /** Emits the assembled draft when the user clicks Publish. */
  publish: [draft: BlogDraft];
  /** Emits the assembled draft when the user clicks Export. */
  exportDraft: [draft: BlogDraft];
  /** Emits the selected File so the platform can upload it to S3. */
  coverImageSelected: [file: File];
}>();

const title = ref(props.initialPost?.title ?? "");
const slug = ref(props.initialPost?.slug ?? "");
const date = ref(props.initialPost?.date ?? todayAsIsoDate());
const summary = ref(props.initialPost?.summary ?? "");
const excerpt = ref(props.initialPost?.excerpt ?? "");
const tags = ref<string[]>([...(props.initialPost?.tags ?? [])]);
const readingTime = ref(props.initialPost?.readingTime ?? 1);
const content = ref(props.initialPost?.content ?? "");
const coverPreview = ref<string | undefined>(props.initialPost?.coverImage);
const tagInput = ref("");
const activePane = ref<"write" | "preview">("write");
const slugEdited = ref(!!props.initialPost);
const textareaEl = ref<HTMLTextAreaElement | null>(null);
const selectedSeriesKey = ref("none");
const seriesId = ref(props.initialPost?.series?.id ?? "");
const seriesTitle = ref(props.initialPost?.series?.title ?? "");
const seriesPart = ref(props.initialPost?.series?.part ?? 1);
const seriesTotal = ref<number | undefined>(props.initialPost?.series?.total);

// Populate all fields when the post changes.
watch(
  () => props.initialPost,
  (post) => {
    if (!post) return;
    title.value = post.title;
    slug.value = post.slug;
    date.value = post.date;
    summary.value = post.summary;
    excerpt.value = post.excerpt ?? "";
    tags.value = [...post.tags];
    readingTime.value = post.readingTime ?? 1;
    content.value = post.content;
    coverPreview.value = post.coverImage;
    seriesId.value = post.series?.id ?? "";
    seriesTitle.value = post.series?.title ?? "";
    seriesPart.value = post.series?.part ?? 1;
    seriesTotal.value = post.series?.total;
    slugEdited.value = true;
  },
);

// Derive which dropdown item is selected. Re-runs if existingSeries loads after initialPost.
watch(
  [() => props.initialPost, () => props.existingSeries],
  ([post, existing]) => {
    if (!post?.series) {
      selectedSeriesKey.value = "none";
      return;
    }
    const inList = existing.some(
      (s: { id: string }) => s.id === post.series!.id,
    );
    selectedSeriesKey.value = inList ? post.series!.id : "__new__";
  },
);

const renderedHtml = computed(() => marked.parse(content.value) as string);
const canPublish = computed(
  () =>
    title.value.trim().length > 0 &&
    summary.value.trim().length > 0 &&
    content.value.trim().length > 0,
);
const previewUrl = computed(() => coverPreview.value ?? props.coverImageUrl);

function onSeriesKeyChange(e: Event) {
  const key = (e.target as HTMLSelectElement).value;
  selectedSeriesKey.value = key;
  if (key !== "none" && key !== "__new__") {
    const found = props.existingSeries.find((s) => s.id === key);
    if (found) {
      seriesId.value = found.id;
      seriesTitle.value = found.title;
    }
  }
}

function onTitleChange(e: Event) {
  title.value = (e.target as HTMLInputElement).value;
  if (!slugEdited.value) slug.value = generateSlug(title.value);
  readingTime.value = calcReadingTime(content.value);
}

function onContentChange(e: Event) {
  content.value = (e.target as HTMLTextAreaElement).value;
  readingTime.value = calcReadingTime(content.value);
}

function onTagKeydown(e: KeyboardEvent) {
  if (e.key === "Enter" || e.key === ",") {
    e.preventDefault();
    const tag = generateSlug(tagInput.value);
    if (tag && !tags.value.includes(tag)) tags.value = [...tags.value, tag];
    tagInput.value = "";
  }
  if (e.key === "Backspace" && !tagInput.value && tags.value.length) {
    tags.value = tags.value.slice(0, -1);
  }
}

function removeTag(tag: string) {
  tags.value = tags.value.filter((t) => t !== tag);
}

function onCoverChange(e: Event) {
  const file = (e.target as HTMLInputElement).files?.[0];
  if (!file) return;
  emit("coverImageSelected", file);
  const reader = new FileReader();
  reader.onload = () => {
    coverPreview.value = reader.result as string;
  };
  reader.readAsDataURL(file);
}

function applyFormat(item: ToolbarItem) {
  const el = textareaEl.value;
  if (!el) return;

  const start = el.selectionStart;
  const end = el.selectionEnd;
  const cur = content.value;
  let newContent: string;
  let newCursor: number;

  if (item.wrap) {
    const [before, after] = item.wrap;
    const sel = cur.slice(start, end) || "text";
    newContent = cur.slice(0, start) + before + sel + after + cur.slice(end);
    newCursor = start + before.length + sel.length + after.length;
  } else if (item.prefix) {
    const lineStart = cur.lastIndexOf("\n", start - 1) + 1;
    newContent = cur.slice(0, lineStart) + item.prefix + cur.slice(lineStart);
    newCursor = start + item.prefix.length;
  } else if (item.block) {
    newContent = cur.slice(0, start) + item.block + cur.slice(end);
    newCursor = start + item.block.length;
  } else {
    return;
  }

  content.value = newContent;
  setTimeout(() => {
    el.selectionStart = el.selectionEnd = newCursor;
    el.focus();
  }, 0);
}

function assembleDraft(): BlogDraft {
  let series: BlogDraft["series"];
  const total = seriesTotal.value;
  if (selectedSeriesKey.value === "__new__") {
    const id = seriesId.value.trim();
    series = id
      ? {
          id,
          title: seriesTitle.value.trim() || id,
          part: seriesPart.value,
          ...(total !== undefined ? { total } : {}),
        }
      : undefined;
  } else if (selectedSeriesKey.value !== "none") {
    const found = props.existingSeries.find(
      (s) => s.id === selectedSeriesKey.value,
    );
    series = found
      ? {
          id: found.id,
          title: found.title,
          part: seriesPart.value,
          ...(total !== undefined ? { total } : {}),
        }
      : undefined;
  }
  return {
    title: title.value,
    slug: slug.value || generateSlug(title.value),
    date: date.value,
    summary: summary.value,
    excerpt: excerpt.value || undefined,
    tags: tags.value,
    readingTime: readingTime.value,
    content: content.value,
    coverImage: props.coverImageUrl ?? coverPreview.value,
    series,
  };
}

function onPublish() {
  if (!canPublish.value) return;
  emit("publish", assembleDraft());
}

function onExport() {
  if (!canPublish.value) return;
  emit("exportDraft", assembleDraft());
}
</script>

<template>
  <div class="be-root">
    <!-- ── Metadata ──────────────────────────────────────────────────────── -->
    <section class="be-meta">
      <div class="be-field be-field--full">
        <label class="be-label">Title <span class="be-required">*</span></label>
        <input
          class="be-input"
          type="text"
          :value="title"
          placeholder="Post title…"
          @input="onTitleChange"
        />
      </div>

      <div class="be-field">
        <label class="be-label">Slug</label>
        <input
          v-model="slug"
          class="be-input"
          type="text"
          placeholder="post-slug"
          @input="slugEdited = true"
        />
      </div>

      <div class="be-field">
        <label class="be-label" for="be-date">Date</label>
        <input
          id="be-date"
          v-model="date"
          class="be-input be-input--date"
          type="date"
        />
      </div>

      <div class="be-field be-field--full">
        <label class="be-label"
          >Summary <span class="be-required">*</span></label
        >
        <textarea
          v-model="summary"
          class="be-input be-input--textarea"
          rows="2"
          placeholder="Short description shown in blog listings…"
        />
      </div>

      <div class="be-field be-field--full">
        <label class="be-label"
          >Excerpt <span class="be-optional">(optional)</span></label
        >
        <textarea
          v-model="excerpt"
          class="be-input be-input--textarea"
          rows="2"
          placeholder="Longer teaser for social previews…"
        />
      </div>

      <div class="be-field">
        <label class="be-label">Tags</label>
        <div class="be-tags">
          <span v-for="tag in tags" :key="tag" class="be-tag">
            {{ tag }}
            <button
              type="button"
              class="be-tag__remove"
              :aria-label="`Remove tag ${tag}`"
              @click="removeTag(tag)"
            >
              ×
            </button>
          </span>
          <input
            v-model="tagInput"
            class="be-tag-input"
            type="text"
            placeholder="Add tag, press Enter…"
            @keydown="onTagKeydown"
          />
        </div>
      </div>

      <div class="be-field">
        <label class="be-label" for="be-reading-time">Reading time (min)</label>
        <input
          id="be-reading-time"
          v-model.number="readingTime"
          class="be-input be-input--narrow"
          type="number"
          min="1"
        />
      </div>

      <div class="be-field be-field--cover">
        <label class="be-label">Cover Image</label>
        <div class="be-cover">
          <img
            v-if="previewUrl"
            class="be-cover__preview"
            :src="previewUrl"
            alt="Cover preview"
          />
          <label class="be-cover__pick">
            {{ previewUrl ? "Replace" : "Choose image" }}
            <input
              type="file"
              accept="image/*"
              hidden
              @change="onCoverChange"
            />
          </label>
        </div>
      </div>

      <div class="be-field-group-label">
        Series <span class="be-optional">(optional)</span>
      </div>

      <div class="be-field be-field--full">
        <label class="be-label" for="be-series">Series</label>
        <select
          id="be-series"
          class="be-input be-input--select"
          :value="selectedSeriesKey"
          @change="onSeriesKeyChange"
        >
          <option value="none">— None —</option>
          <option v-for="s in existingSeries" :key="s.id" :value="s.id">
            {{ s.title }}
          </option>
          <option value="__new__">+ New series…</option>
        </select>
      </div>

      <template v-if="selectedSeriesKey === '__new__'">
        <div class="be-field">
          <label class="be-label">Series ID</label>
          <input
            v-model="seriesId"
            class="be-input"
            type="text"
            placeholder="e.g. go-backend"
          />
        </div>
        <div class="be-field">
          <label class="be-label">Series Title</label>
          <input
            v-model="seriesTitle"
            class="be-input"
            type="text"
            placeholder="e.g. Go Backend Series"
          />
        </div>
      </template>

      <div
        v-if="selectedSeriesKey !== 'none'"
        class="be-field be-field--narrow-pair"
      >
        <div>
          <label class="be-label">Part</label>
          <input
            v-model.number="seriesPart"
            class="be-input be-input--narrow"
            type="number"
            min="1"
          />
        </div>
        <div>
          <label class="be-label"
            >Total Parts <span class="be-optional">(optional)</span></label
          >
          <input
            class="be-input be-input--narrow"
            type="number"
            min="1"
            :value="seriesTotal"
            placeholder="auto"
            @input="
              seriesTotal = ($event.target as HTMLInputElement).value
                ? +($event.target as HTMLInputElement).value
                : undefined
            "
          />
          <span class="be-hint"
            >Leave blank to derive from published post count</span
          >
        </div>
      </div>
    </section>

    <!-- ── Editor ────────────────────────────────────────────────────────── -->
    <section class="be-editor">
      <div class="be-toolbar" role="toolbar" aria-label="Formatting">
        <!-- Mobile pane toggle — hidden on desktop via CSS -->
        <div class="be-pane-toggle" role="group" aria-label="Editor mode">
          <button
            type="button"
            class="be-pane-toggle__btn"
            :class="{ 'be-pane-toggle__btn--active': activePane === 'write' }"
            @click="activePane = 'write'"
          >
            Write
          </button>
          <button
            type="button"
            class="be-pane-toggle__btn"
            :class="{
              'be-pane-toggle__btn--active': activePane === 'preview',
            }"
            @click="activePane = 'preview'"
          >
            Preview
          </button>
        </div>

        <div class="be-toolbar__tools">
          <button
            v-for="item in BLOG_EDITOR_TOOLBAR"
            :key="item.label"
            type="button"
            class="be-toolbar__btn"
            :title="item.label"
            :aria-label="item.label"
            @click="applyFormat(item)"
          >
            {{ item.icon }}
          </button>
        </div>
      </div>

      <div class="be-panes">
        <div
          class="be-pane be-pane--write"
          :class="{ 'be-pane--hidden': activePane === 'preview' }"
        >
          <div class="be-pane__label">Markdown</div>
          <textarea
            ref="textareaEl"
            class="be-pane__textarea"
            :value="content"
            placeholder="Write your post in markdown…"
            spellcheck="true"
            @input="onContentChange"
          />
        </div>

        <div
          class="be-pane be-pane--preview"
          :class="{ 'be-pane--hidden': activePane === 'write' }"
        >
          <div class="be-pane__label">Preview</div>
          <!-- content is authored by the admin user — trusted HTML -->
          <!-- eslint-disable-next-line vue/no-v-html -->
          <div class="be-pane__preview prose" v-html="renderedHtml" />
        </div>
      </div>
    </section>

    <!-- ── Footer ────────────────────────────────────────────────────────── -->
    <footer class="be-footer">
      <span class="be-footer__meta">~{{ readingTime }} min read</span>
      <div class="be-footer__actions">
        <button
          type="button"
          class="be-export"
          :disabled="!canPublish"
          @click="onExport"
        >
          Export
        </button>
        <button
          type="button"
          class="be-publish"
          :disabled="!canPublish"
          @click="onPublish"
        >
          Publish Post
        </button>
      </div>
    </footer>
  </div>
</template>

<style lang="scss">
@use "packages/tokens/src/components/blog-editor";
</style>

// packages/ng-lib/src/lib/components/blog-editor/blog-editor.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  ViewChild,
  computed,
  effect,
  inject,
  input,
  output,
  signal,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { marked } from 'marked';
import { BLOG_EDITOR_TOOLBAR, calcReadingTime, generateSlug, todayAsIsoDate } from '@m2s2/utils';
import type { ToolbarItem } from '@m2s2/utils';
import type { BlogDraft, BlogPost } from '../../models/blog';

@Component({
  selector: 'm2s2-blog-editor',
  templateUrl: './blog-editor.component.html',
  styleUrls: ['./blog-editor.component.scss'],
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule],
})
export class BlogEditorComponent {
  /** Populate fields when editing an existing post. */
  initialPost = input<BlogPost | undefined>(undefined);

  /** Set to the S3 URL after the platform has uploaded the selected cover image. */
  coverImageUrl = input<string | undefined>(undefined);

  /** Emits the assembled draft when the user clicks Publish. */
  publish = output<BlogDraft>();

  /** Emits the assembled draft when the user clicks Export. */
  exportDraft = output<BlogDraft>();

  /** Emits the selected File so the platform can upload it to S3. */
  coverImageSelected = output<File>();

  readonly toolbarItems = BLOG_EDITOR_TOOLBAR;

  readonly title       = signal('');
  readonly slug        = signal('');
  readonly date        = signal(todayAsIsoDate());
  readonly summary     = signal('');
  readonly excerpt     = signal('');
  readonly tags        = signal<string[]>([]);
  readonly readingTime = signal(1);
  readonly content     = signal('');
  readonly coverPreviewUrl = signal<string | undefined>(undefined);
  readonly activePane      = signal<'write' | 'preview'>('write');

  existingSeries = input<Array<{ id: string; title: string }>>([]);

  readonly selectedSeriesKey = signal<string>('none');
  readonly seriesId          = signal('');
  readonly seriesTitle       = signal('');
  readonly seriesPart        = signal(1);
  readonly seriesTotal       = signal(1);

  tagInput = '';
  slugEdited = false;

  private readonly sanitizer = inject(DomSanitizer);

  @ViewChild('editorTextarea') private editorTextarea?: ElementRef<HTMLTextAreaElement>;

  readonly renderedContent = computed<SafeHtml>(() => {
    const html = marked.parse(this.content()) as string;
    return this.sanitizer.bypassSecurityTrustHtml(html);
  });

  readonly canPublish = computed(() =>
    this.title().trim().length > 0 &&
    this.summary().trim().length > 0 &&
    this.content().trim().length > 0,
  );

  constructor() {
    // Populate all fields except series key when the post loads.
    effect(() => {
      const post = this.initialPost();
      if (!post) return;
      this.title.set(post.title);
      this.slug.set(post.slug);
      this.date.set(post.date);
      this.summary.set(post.summary);
      this.excerpt.set(post.excerpt ?? '');
      this.tags.set([...post.tags]);
      this.readingTime.set(post.readingTime ?? 1);
      this.content.set(post.content);
      this.coverPreviewUrl.set(post.coverImage);
      this.seriesId.set(post.series?.id ?? '');
      this.seriesTitle.set(post.series?.title ?? '');
      this.seriesPart.set(post.series?.part ?? 1);
      this.seriesTotal.set(post.series?.total ?? 1);
      this.slugEdited = true;
    });

    // Derive which dropdown item to select. Runs again if existingSeries loads
    // after initialPost so the key resolves correctly either way.
    effect(() => {
      const post = this.initialPost();
      const existing = this.existingSeries();
      if (!post?.series) {
        this.selectedSeriesKey.set('none');
        return;
      }
      const inList = existing.some(s => s.id === post.series!.id);
      this.selectedSeriesKey.set(inList ? post.series!.id : '__new__');
    });
  }

  onSeriesKeyChange(key: string): void {
    this.selectedSeriesKey.set(key);
    if (key !== 'none' && key !== '__new__') {
      const found = this.existingSeries().find(s => s.id === key);
      if (found) {
        this.seriesId.set(found.id);
        this.seriesTitle.set(found.title);
      }
    }
  }

  onTitleChange(value: string): void {
    this.title.set(value);
    if (!this.slugEdited) {
      this.slug.set(generateSlug(value));
    }
    this.readingTime.set(calcReadingTime(this.content()));
  }

  onContentChange(value: string): void {
    this.content.set(value);
    this.readingTime.set(calcReadingTime(value));
  }

  onTagKeydown(event: KeyboardEvent): void {
    if (event.key === 'Enter' || event.key === ',') {
      event.preventDefault();
      const tag = generateSlug(this.tagInput);
      if (tag && !this.tags().includes(tag)) {
        this.tags.update(t => [...t, tag]);
      }
      this.tagInput = '';
    }
    if (event.key === 'Backspace' && !this.tagInput && this.tags().length) {
      this.tags.update(t => t.slice(0, -1));
    }
  }

  removeTag(tag: string): void {
    this.tags.update(t => t.filter(x => x !== tag));
  }

  onCoverChange(event: Event): void {
    const file = (event.target as HTMLInputElement).files?.[0];
    if (!file) return;
    this.coverImageSelected.emit(file);
    const reader = new FileReader();
    reader.onload = () => this.coverPreviewUrl.set(reader.result as string);
    reader.readAsDataURL(file);
  }

  applyFormat(item: ToolbarItem): void {
    const el = this.editorTextarea?.nativeElement;
    if (!el) return;

    const start = el.selectionStart;
    const end   = el.selectionEnd;
    const cur   = this.content();
    let newContent: string;
    let newCursor: number;

    if (item.wrap) {
      const [before, after] = item.wrap;
      const sel = cur.slice(start, end) || 'text';
      newContent = cur.slice(0, start) + before + sel + after + cur.slice(end);
      newCursor  = start + before.length + sel.length + after.length;
    } else if (item.prefix) {
      const lineStart = cur.lastIndexOf('\n', start - 1) + 1;
      newContent = cur.slice(0, lineStart) + item.prefix + cur.slice(lineStart);
      newCursor  = start + item.prefix.length;
    } else if (item.block) {
      newContent = cur.slice(0, start) + item.block + cur.slice(end);
      newCursor  = start + item.block.length;
    } else {
      return;
    }

    this.content.set(newContent);
    setTimeout(() => { el.selectionStart = el.selectionEnd = newCursor; el.focus(); }, 0);
  }

  onPublish(): void {
    if (!this.canPublish()) return;
    this.publish.emit(this.assembleDraft());
  }

  onExport(): void {
    if (!this.canPublish()) return;
    this.exportDraft.emit(this.assembleDraft());
  }

  private assembleDraft(): BlogDraft {
    const key = this.selectedSeriesKey();
    let series: BlogDraft['series'];
    if (key === '__new__') {
      const id = this.seriesId().trim();
      series = id ? { id, title: this.seriesTitle().trim() || id, part: this.seriesPart(), total: this.seriesTotal() } : undefined;
    } else if (key !== 'none') {
      const found = this.existingSeries().find(s => s.id === key);
      series = found ? { id: found.id, title: found.title, part: this.seriesPart(), total: this.seriesTotal() } : undefined;
    }
    return {
      title:       this.title(),
      slug:        this.slug() || generateSlug(this.title()),
      date:        this.date(),
      summary:     this.summary(),
      excerpt:     this.excerpt() || undefined,
      tags:        this.tags(),
      readingTime: this.readingTime(),
      content:     this.content(),
      coverImage:  this.coverImageUrl() ?? this.coverPreviewUrl(),
      series,
    };
  }
}

<div class="be-root">

  <!-- ── Metadata ───────────────────────────────────────────────────────────── -->
  <section class="be-meta">

    <div class="be-field be-field--full">
      <label class="be-label">Title <span class="be-required">*</span></label>
      <input
        class="be-input"
        type="text"
        [ngModel]="title()"
        (ngModelChange)="onTitleChange($event)"
        placeholder="Post title…"
      />
    </div>

    <div class="be-field">
      <label class="be-label">Slug</label>
      <input
        class="be-input"
        type="text"
        [ngModel]="slug()"
        (ngModelChange)="slug.set($event); slugEdited = true"
        placeholder="post-slug"
      />
    </div>

    <div class="be-field">
      <label class="be-label" for="be-date">Date</label>
      <input
        id="be-date"
        class="be-input be-input--date"
        type="date"
        [ngModel]="date()"
        (ngModelChange)="date.set($event)"
      />
    </div>

    <div class="be-field be-field--full">
      <label class="be-label">Summary <span class="be-required">*</span></label>
      <textarea
        class="be-input be-input--textarea"
        rows="2"
        [ngModel]="summary()"
        (ngModelChange)="summary.set($event)"
        placeholder="Short description shown in blog listings…"
      ></textarea>
    </div>

    <div class="be-field be-field--full">
      <label class="be-label">Excerpt <span class="be-optional">(optional)</span></label>
      <textarea
        class="be-input be-input--textarea"
        rows="2"
        [ngModel]="excerpt()"
        (ngModelChange)="excerpt.set($event)"
        placeholder="Longer teaser for social previews…"
      ></textarea>
    </div>

    <div class="be-field">
      <label class="be-label">Tags</label>
      <div class="be-tags">
        @for (tag of tags(); track tag) {
          <span class="be-tag">
            {{ tag }}
            <button type="button" class="be-tag__remove" (click)="removeTag(tag)" aria-label="Remove tag">×</button>
          </span>
        }
        <input
          class="be-tag-input"
          type="text"
          [(ngModel)]="tagInput"
          (keydown)="onTagKeydown($event)"
          placeholder="Add tag, press Enter…"
        />
      </div>
    </div>

    <div class="be-field">
      <label class="be-label" for="be-reading-time">Reading time (min)</label>
      <input
        id="be-reading-time"
        class="be-input be-input--narrow"
        type="number"
        min="1"
        [ngModel]="readingTime()"
        (ngModelChange)="readingTime.set(+$event)"
      />
    </div>

    <div class="be-field be-field--cover">
      <label class="be-label">Cover Image</label>
      <div class="be-cover">
        @if (coverPreviewUrl() || coverImageUrl()) {
          <img
            class="be-cover__preview"
            [src]="coverPreviewUrl() ?? coverImageUrl()"
            alt="Cover preview"
          />
        }
        <label class="be-cover__pick">
          {{ (coverPreviewUrl() || coverImageUrl()) ? 'Replace' : 'Choose image' }}
          <input type="file" accept="image/*" (change)="onCoverChange($event)" hidden />
        </label>
      </div>
    </div>

    <div class="be-field-group-label">Series <span class="be-optional">(optional)</span></div>

    <div class="be-field be-field--full">
      <label class="be-label" for="be-series">Series</label>
      <select
        id="be-series"
        class="be-input be-input--select"
        [ngModel]="selectedSeriesKey()"
        (ngModelChange)="onSeriesKeyChange($event)"
      >
        <option value="none">— None —</option>
        @for (s of existingSeries(); track s.id) {
          <option [value]="s.id">{{ s.title }}</option>
        }
        <option value="__new__">+ New series…</option>
      </select>
    </div>

    @if (selectedSeriesKey() === '__new__') {
      <div class="be-field">
        <label class="be-label">Series ID</label>
        <input
          class="be-input"
          type="text"
          [ngModel]="seriesId()"
          (ngModelChange)="seriesId.set($event)"
          placeholder="e.g. go-backend"
        />
      </div>
      <div class="be-field">
        <label class="be-label">Series Title</label>
        <input
          class="be-input"
          type="text"
          [ngModel]="seriesTitle()"
          (ngModelChange)="seriesTitle.set($event)"
          placeholder="e.g. Go Backend Series"
        />
      </div>
    }

    @if (selectedSeriesKey() !== 'none') {
      <div class="be-field be-field--narrow-pair">
        <div>
          <label class="be-label" for="series-part">Part</label>
          <input
            id="series-part"
            class="be-input be-input--narrow"
            type="number"
            min="1"
            [ngModel]="seriesPart()"
            (ngModelChange)="seriesPart.set(+$event)"
          />
        </div>
        <div>
          <label class="be-label" for="series-total">Total Parts <span class="be-optional">(optional)</span></label>
          <input
            id="series-total"
            class="be-input be-input--narrow"
            type="number"
            min="1"
            [ngModel]="seriesTotal()"
            (ngModelChange)="seriesTotal.set($event ? +$event : undefined)"
            placeholder="auto"
          />
          <span class="be-hint">Leave blank to derive from published post count</span>
        </div>
      </div>
    }

  </section>

  <!-- ── Editor ─────────────────────────────────────────────────────────────── -->
  <section class="be-editor">

    <div class="be-toolbar" role="toolbar" aria-label="Formatting">
      <!-- Mobile pane toggle — hidden on desktop via CSS -->
      <div class="be-pane-toggle" role="group" aria-label="Editor mode">
        <button
          type="button"
          class="be-pane-toggle__btn"
          [class.be-pane-toggle__btn--active]="activePane() === 'write'"
          (click)="activePane.set('write')"
        >Write</button>
        <button
          type="button"
          class="be-pane-toggle__btn"
          [class.be-pane-toggle__btn--active]="activePane() === 'preview'"
          (click)="activePane.set('preview')"
        >Preview</button>
      </div>

      <div class="be-toolbar__tools">
        @for (item of toolbarItems; track item.label) {
          <button
            type="button"
            class="be-toolbar__btn"
            [title]="item.label"
            [attr.aria-label]="item.label"
            (click)="applyFormat(item)"
          >{{ item.icon }}</button>
        }
      </div>
    </div>

    <div class="be-panes">
      <div class="be-pane be-pane--write" [class.be-pane--hidden]="activePane() === 'preview'">
        <div class="be-pane__label">Markdown</div>
        <textarea
          #editorTextarea
          class="be-pane__textarea"
          [ngModel]="content()"
          (ngModelChange)="onContentChange($event)"
          placeholder="Write your post in markdown…"
          spellcheck="true"
        ></textarea>
      </div>

      <div class="be-pane be-pane--preview" [class.be-pane--hidden]="activePane() === 'write'">
        <div class="be-pane__label">Preview</div>
        <div class="be-pane__preview prose" [innerHTML]="renderedContent()"></div>
      </div>
    </div>

  </section>

  <!-- ── Footer ─────────────────────────────────────────────────────────────── -->
  <footer class="be-footer">
    <span class="be-footer__meta">~{{ readingTime() }} min read</span>
    <div class="be-footer__actions">
      <button
        type="button"
        class="be-export"
        [disabled]="!canPublish()"
        (click)="onExport()"
      >Export</button>
      <button
        type="button"
        class="be-publish"
        [disabled]="!canPublish()"
        (click)="onPublish()"
      >Publish Post</button>
    </div>
  </footer>

</div>
