// packages/vue-lib/src/components/Panel/Panel.vue
<script setup lang="ts">
import type { M2S2PanelData, DialogAction } from "@m2s2/models";

const props = withDefaults(
  defineProps<{
    data: M2S2PanelData;
    open: boolean;
  }>(),
  {},
);

const emit = defineEmits<{
  action: [value: unknown];
  close: [];
}>();

const side = () => props.data.side ?? "right";

function onAction(action: DialogAction): void {
  emit("action", action.value);
}

function onBackdropClick(): void {
  if (!props.data.modal) emit("close");
}
</script>

<template>
  <Teleport to="body">
    <Transition name="panel-overlay-fade">
      <div
        v-if="open"
        class="m2s2-panel-overlay"
        @click.self="onBackdropClick"
      />
    </Transition>
    <Transition :name="`panel-slide-${side()}`">
      <div
        v-if="open"
        class="m2s2-panel-content"
        :class="`m2s2-panel-content--${side()}`"
        :style="data.width ? { '--panel-width': data.width } : {}"
        role="dialog"
        :aria-modal="true"
        :aria-labelledby="'panel-title'"
      >
        <div class="panel-header">
          <div class="panel-header-text">
            <h2 id="panel-title" class="panel-title">
              {{ data.title }}
            </h2>
            <p v-if="data.subtitle" class="panel-subtitle">
              {{ data.subtitle }}
            </p>
          </div>
          <button
            v-if="!data.modal"
            class="panel-close"
            aria-label="Close"
            @click="emit('close')"
          >
            &#x2715;
          </button>
        </div>

        <div class="panel-body">
          <p v-if="data.message && !$slots.default" class="panel-message">
            {{ data.message }}
          </p>
          <slot />
        </div>

        <div v-if="data.actions?.length" class="panel-footer">
          <button
            v-for="action in data.actions"
            :key="action.label"
            class="panel-btn"
            :class="`panel-btn--${action.variant ?? 'secondary'}`"
            @click="onAction(action)"
          >
            {{ action.label }}
          </button>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<style lang="scss">
@use "packages/tokens/src/components/panel";

.m2s2-panel-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.45);
  z-index: var(--z-modal, 300);
}

.m2s2-panel-content {
  position: fixed;
  top: 0;
  bottom: 0;
  z-index: var(--z-modal, 300);
  width: min(var(--panel-width, 480px), 100vw);
  max-width: 100vw;
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  box-shadow: var(--shadow-xl);
  display: flex;
  flex-direction: column;
  overflow: hidden;

  &--right {
    right: 0;
    border-radius: var(--radius-lg) 0 0 var(--radius-lg);
  }

  &--left {
    left: 0;
    border-radius: 0 var(--radius-lg) var(--radius-lg) 0;
  }
}

// Overlay fade
.panel-overlay-fade-enter-active,
.panel-overlay-fade-leave-active {
  transition: opacity 200ms ease;
}
.panel-overlay-fade-enter-from,
.panel-overlay-fade-leave-to {
  opacity: 0;
}

// Right slide
.panel-slide-right-enter-active,
.panel-slide-right-leave-active {
  transition: transform 220ms ease;
}
.panel-slide-right-enter-from,
.panel-slide-right-leave-to {
  transform: translateX(100%);
}

// Left slide
.panel-slide-left-enter-active,
.panel-slide-left-leave-active {
  transition: transform 220ms ease;
}
.panel-slide-left-enter-from,
.panel-slide-left-leave-to {
  transform: translateX(-100%);
}
</style>

// packages/ng-lib/src/lib/components/panel/panel.component.ts
import { Component, inject } from '@angular/core';
import { NgComponentOutlet } from '@angular/common';
import { MAT_DIALOG_DATA, MatDialogRef } from '@angular/material/dialog';
import { M2S2PanelData, DialogAction } from '../../models';

@Component({
  selector: 'm2s2-panel',
  templateUrl: './panel.component.html',
  styleUrls: ['./panel.component.scss'],
  standalone: true,
  imports: [NgComponentOutlet],
})
export class M2S2PanelComponent {
  readonly data = inject<M2S2PanelData>(MAT_DIALOG_DATA);
  readonly ref  = inject(MatDialogRef<M2S2PanelComponent>);

  close(value?: unknown): void {
    this.ref.close(value);
  }

  action(a: DialogAction): void {
    this.ref.close(a.value);
  }
}

<div class="panel-header">
  <div class="panel-header-text">
    <h2 class="panel-title">{{ data.title }}</h2>
    @if (data.subtitle) {
      <p class="panel-subtitle">{{ data.subtitle }}</p>
    }
  </div>
  @if (!data.modal) {
    <button class="panel-close" aria-label="Close" (click)="close(null)">&#x2715;</button>
  }
</div>

<div class="panel-body">
  @if (data.bodyComponent) {
    <ng-container
      [ngComponentOutlet]="data.bodyComponent"
      [ngComponentOutletInputs]="data.bodyInputs ?? {}">
    </ng-container>
  } @else if (data.message) {
    <p class="panel-message">{{ data.message }}</p>
  }
</div>

@if (data.actions?.length) {
  <div class="panel-footer">
    @for (a of data.actions; track a.label) {
      <button
        class="panel-btn"
        [class]="'panel-btn--' + (a.variant ?? 'secondary')"
        (click)="action(a)">
        {{ a.label }}
      </button>
    }
  </div>
}
