// packages/ng-lib/src/lib/components/process-steps/process-steps.component.ts
import { Component, input } from '@angular/core';
import { ProcessStep } from '../../models/process-steps/process-steps.model';

@Component({
  selector: 'm2s2-process-steps',
  templateUrl: './process-steps.component.html',
  styleUrls: ['./process-steps.component.scss'],
  standalone: true,
})
export class ProcessStepsComponent {
  steps = input.required<ProcessStep[]>();
}

<ol class="ps-steps">
  @for (step of steps(); track step.num; let last = $last) {
    <li class="ps-step">
      <span class="ps-num">{{ step.num }}</span>
      <span class="ps-name">{{ step.name }}</span>
      <span class="ps-desc">{{ step.desc }}</span>
    </li>
    @if (!last) {
      <li class="ps-divider" aria-hidden="true">&#8594;</li>
    }
  }
</ol>

// packages/react-lib/src/components/ProcessSteps/ProcessSteps.tsx
import { Fragment } from 'react';
import { ProcessStep } from '@m2s2/models';
import './ProcessSteps.scss';

interface ProcessStepsProps {
  steps: ProcessStep[];
}

export function ProcessSteps({ steps }: ProcessStepsProps) {
  return (
    <ol className="ps-steps">
      {steps.map((step, i) => (
        <Fragment key={step.num}>
          <li className="ps-step">
            <span className="ps-num">{step.num}</span>
            <span className="ps-name">{step.name}</span>
            <span className="ps-desc">{step.desc}</span>
          </li>
          {i < steps.length - 1 && (
            <li className="ps-divider" aria-hidden="true">&#8594;</li>
          )}
        </Fragment>
      ))}
    </ol>
  );
}
