// packages/ng-lib/src/lib/components/loading-button/loading-button.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';

@Component({
  selector: 'm2s2-loading-button',
  template: `
    <button [disabled]="loading() || disabled()" [attr.aria-busy]="loading()">
      @if (loading()) { <span class="m2s2-btn-spinner" aria-hidden="true"></span> }
      @if (!loading() || !loadingText()) {
        <ng-content />
      } @else {
        {{ loadingText() }}
      }
    </button>
  `,
  styleUrls: ['./loading-button.component.scss'],
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LoadingButtonComponent {
  loading     = input<boolean>(false);
  loadingText = input<string | undefined>(undefined);
  disabled    = input<boolean>(false);
}

// packages/react-lib/src/components/LoadingButton/LoadingButton.tsx
import { ButtonHTMLAttributes, ReactNode } from 'react';
import './LoadingButton.scss';

export interface LoadingButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  loading?: boolean;
  loadingText?: string;
  children: ReactNode;
}

export function LoadingButton({
  loading = false,
  loadingText,
  children,
  disabled,
  ...rest
}: LoadingButtonProps) {
  return (
    <button disabled={loading || disabled} aria-busy={loading} {...rest}>
      {loading && <span className="m2s2-btn-spinner" aria-hidden="true" />}
      {loading && loadingText ? loadingText : children}
    </button>
  );
}
