// packages/vue-lib/src/components/Footer/Footer.vue
<script setup lang="ts">
import type { FooterConfig } from "@m2s2/models";
import SocialIcon from "./SocialIcon.vue";

defineProps<{ config: FooterConfig }>();

const year = new Date().getFullYear();
</script>

<template>
  <footer class="m2s2-footer">
    <div class="footer-inner">
      <span class="footer-copy">
        &copy; {{ year }} {{ config.brandName }} &mdash; All Rights Reserved
        <span v-if="config.buildVersion" class="footer-build"
          >&middot; {{ config.buildVersion.split("+")[0] }}</span
        >
      </span>
      <nav class="footer-social" aria-label="Social links">
        <a
          v-for="link in config.links"
          :key="link.type"
          :href="link.href"
          class="social-link"
          :title="link.label ?? link.type"
          :aria-label="link.label ?? link.type"
          v-bind="
            link.type !== 'email'
              ? { target: '_blank', rel: 'noopener noreferrer' }
              : {}
          "
        >
          <SocialIcon :type="link.type" />
        </a>
      </nav>
    </div>
  </footer>
</template>

<style lang="scss">
@use "packages/tokens/src/mixins" as m;

.m2s2-footer {
  width: 100%;
  min-height: var(--footer-height, 48px);
  background-color: var(--color-nav-bg);
  color: var(--color-on-nav);
  border-top: 2px solid transparent;
  border-image: var(--gradient-brand) 1;
}

.footer-inner {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: var(--space-3);
  padding: var(--space-3) var(--space-4);
  text-align: center;
  min-height: var(--footer-height, 48px);

  @media (min-width: 576px) {
    flex-direction: row;
    justify-content: space-between;
    text-align: left;
    padding: var(--space-2) var(--space-6);
  }
}

.footer-copy {
  font-size: var(--font-size-sm);
  opacity: 0.85;
}

.footer-social {
  display: flex;
  align-items: center;
  gap: var(--space-3);
}

.social-link {
  @include m.social-link;
}
.social-icon {
  @include m.social-icon;
}

.footer-build {
  display: none;
  margin-left: var(--space-2);
  font-size: 0.6rem;
  font-family: monospace;
  letter-spacing: 0.04em;
  opacity: 0.3;

  @media (min-width: 576px) {
    display: inline;
  }
}
</style>

// packages/react-lib/src/components/Footer/Footer.tsx
import { FooterConfig } from '@m2s2/models';
import './Footer.scss';

interface FooterProps {
  config: FooterConfig;
}

export function Footer({ config }: FooterProps) {
  const year = new Date().getFullYear();

  return (
    <footer className="m2s2-footer">
      <div className="footer-inner">
        <span className="footer-copy">
          &copy; {year} {config.brandName} &mdash; All Rights Reserved
          {config.buildVersion && (
            <span className="footer-build">&middot; {config.buildVersion.split('+')[0]}</span>
          )}
        </span>
        <nav className="footer-social" aria-label="Social links">
          {config.links.map((link) => (
            <a
              key={link.type}
              href={link.href}
              className="social-link"
              title={link.label ?? link.type}
              aria-label={link.label ?? link.type}
              {...(link.type !== 'email' ? { target: '_blank', rel: 'noopener noreferrer' } : {})}
            >
              <SocialIcon type={link.type} />
            </a>
          ))}
        </nav>
      </div>
    </footer>
  );
}

function SocialIcon({ type }: { type: string }) {
  if (type === 'github') {
    return (
      <svg className="social-icon" viewBox="0 0 98 96" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" fill="currentColor">
        <path fillRule="evenodd" clipRule="evenodd" d="M48.854 0C21.839 0 0 22 0 49.217c0 21.756 13.993 40.172 33.405 46.69 2.427.49 3.316-1.059 3.316-2.362 0-1.141-.08-5.052-.08-9.127-13.59 2.934-16.42-5.867-16.42-5.867-2.184-5.704-5.42-7.17-5.42-7.17-4.448-3.015.324-3.015.324-3.015 4.934.326 7.523 5.052 7.523 5.052 4.367 7.496 11.404 5.378 14.235 4.074.404-3.178 1.699-5.378 3.074-6.6-10.839-1.141-22.243-5.378-22.243-24.283 0-5.378 1.94-9.778 5.014-13.2-.485-1.222-2.184-6.275.486-13.038 0 0 4.125-1.304 13.426 5.052a46.97 46.97 0 0 1 12.214-1.63c4.125 0 8.33.571 12.213 1.63 9.302-6.356 13.427-5.052 13.427-5.052 2.67 6.763.97 11.816.485 13.038 3.155 3.422 5.015 7.822 5.015 13.2 0 18.905-11.404 23.06-22.324 24.283 1.78 1.548 3.316 4.481 3.316 9.126 0 6.6-.08 11.897-.08 13.526 0 1.304.89 2.853 3.316 2.364 19.412-6.52 33.405-24.935 33.405-46.691C97.707 22 75.788 0 48.854 0z" />
      </svg>
    );
  }
  if (type === 'linkedin') {
    return (
      <svg className="social-icon" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" fill="currentColor">
        <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 0 1-2.063-2.065 2.064 2.064 0 1 1 2.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
      </svg>
    );
  }
  if (type === 'twitter') {
    return (
      <svg className="social-icon" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" fill="currentColor">
        <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-4.714-6.231-5.401 6.231H2.747l7.73-8.835L1.254 2.25H8.08l4.253 5.622 5.91-5.622Zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
      </svg>
    );
  }
  if (type === 'email') {
    return (
      <svg className="social-icon" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" fill="currentColor">
        <path d="M20 4H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 4-8 5-8-5V6l8 5 8-5v2z" />
      </svg>
    );
  }
  return null;
}
