// packages/react-lib/src/components/SectionHeader/SectionHeader.tsx
import { SectionHeaderConfig } from '@m2s2/models';
import './SectionHeader.scss';

interface SectionHeaderProps {
  config: SectionHeaderConfig;
}

export function SectionHeader({ config }: SectionHeaderProps) {
  return (
    <div className="m2s2-section-header">
      <h2 className="sh-label">{config.label}</h2>
      {config.subtitle && <p className="sh-subtitle">{config.subtitle}</p>}
    </div>
  );
}

// packages/ng-lib/src/lib/components/section-header/section-header.component.ts
import { Component, input } from "@angular/core";
import { SectionHeaderConfig } from "../../models/section-header/section-header.model";

@Component({
  selector: "m2s2-section-header",
  templateUrl: "./section-header.component.html",
  styleUrls: ["./section-header.component.scss"],
  standalone: true,
})
export class SectionHeaderComponent {
  config = input.required<SectionHeaderConfig>();
}

<h2 class="sh-label">{{ config().label }}</h2>
@if (config().subtitle) {
  <p class="sh-subtitle">{{ config().subtitle }}</p>
}
