// packages/ng-lib/src/lib/components/subscribe-form/subscribe-form.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  OnInit,
  input,
  signal,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import { validateEmail } from '@m2s2/utils';
import { Observable } from 'rxjs';

type SubmitState = 'idle' | 'submitting' | 'done' | 'error';

@Component({
  selector: 'm2s2-subscribe-form',
  templateUrl: './subscribe-form.component.html',
  styleUrls: ['./subscribe-form.component.scss'],
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule],
})
export class SubscribeFormComponent implements OnInit {
  /** 'anon' shows email+name inputs. 'auth' shows a one-click subscribe/unsubscribe toggle. */
  mode = input<'anon' | 'auth'>('anon');

  /** Called in anon mode when the user submits their email/name. */
  subscribeAnon = input<(email: string, name: string) => Observable<unknown>>();

  /** Called in auth mode when the user clicks Subscribe. */
  subscribeAuth = input<() => Observable<unknown>>();

  /** Called in auth mode when the user clicks Unsubscribe. */
  unsubscribeAuth = input<() => Observable<unknown>>();

  initialState = input<SubmitState>('idle');

  email = '';
  name  = '';
  readonly state      = signal<SubmitState>('idle');
  readonly subscribed = signal(false);

  ngOnInit(): void {
    this.state.set(this.initialState());
  }

  get emailValid(): boolean {
    return validateEmail(this.email);
  }

  submit(): void {
    if (this.state() === 'submitting') return;

    if (this.mode() === 'auth') {
      if (this.subscribed()) {
        const fn = this.unsubscribeAuth();
        if (!fn) return;
        this.state.set('submitting');
        fn().subscribe({
          next:  () => { this.subscribed.set(false); this.state.set('idle'); },
          error: () => this.state.set('error'),
        });
      } else {
        const fn = this.subscribeAuth();
        if (!fn) return;
        this.state.set('submitting');
        fn().subscribe({
          next:  () => { this.subscribed.set(true); this.state.set('done'); },
          error: () => this.state.set('error'),
        });
      }
    } else {
      if (!this.emailValid) return;
      const fn = this.subscribeAnon();
      if (!fn) return;
      this.state.set('submitting');
      fn(this.email.trim(), this.name.trim()).subscribe({
        next:  () => this.state.set('done'),
        error: () => this.state.set('error'),
      });
    }
  }
}

<!-- ── Anonymous mode: email + name form ─────────────────────────────────── -->
@if (mode() === "anon") {
  @if (state() !== "done") {
    <div class="sub-form">
      <input
        class="sub-input"
        type="text"
        placeholder="Your name (optional)"
        aria-label="Your name (optional)"
        [(ngModel)]="name"
        [disabled]="state() === 'submitting'"
      />
      <input
        class="sub-input"
        type="email"
        placeholder="your@email.com"
        aria-label="Email address"
        [(ngModel)]="email"
        [disabled]="state() === 'submitting'"
      />
      <button
        class="sub-btn"
        [disabled]="!emailValid || state() === 'submitting'"
        (click)="submit()"
      >
        {{ state() === "submitting" ? "Submitting…" : "Subscribe" }}
      </button>
      @if (state() === "error") {
        <p role="alert" class="sub-feedback sub-feedback--error">
          Something went wrong — please try again.
        </p>
      }
    </div>
  } @else {
    <div role="status" class="sub-success">
      <span class="sub-success-icon" aria-hidden="true">✓</span>
      <p class="sub-success-text">
        Check your email to confirm your subscription.
      </p>
    </div>
  }
}

<!-- ── Auth mode: one-click toggle ──────────────────────────────────────── -->
@if (mode() === "auth") {
  <div class="sub-auth">
    @if (!subscribed()) {
      <button
        class="sub-btn"
        [disabled]="state() === 'submitting'"
        (click)="submit()"
      >
        {{
          state() === "submitting"
            ? "Subscribing…"
            : "Subscribe to Blog Updates"
        }}
      </button>
      @if (state() === "done") {
        <p role="status" class="sub-feedback sub-feedback--success">
          You're subscribed!
        </p>
      }
    } @else {
      <span class="sub-subscribed-label">✓ Subscribed to blog updates</span>
      <button
        class="sub-btn sub-btn--unsub"
        [disabled]="state() === 'submitting'"
        (click)="submit()"
      >
        {{ state() === "submitting" ? "Unsubscribing…" : "Unsubscribe" }}
      </button>
    }
    @if (state() === "error") {
      <p role="alert" class="sub-feedback sub-feedback--error">
        Something went wrong — please try again.
      </p>
    }
  </div>
}

// packages/vue-lib/src/components/SubscribeForm/SubscribeForm.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import { validateEmail } from "@m2s2/utils";

type SubmitState = "idle" | "submitting" | "done" | "error";
type Mode = "anon" | "auth";

const props = withDefaults(
  defineProps<{
    mode?: Mode;
    subscribeAnon?: (email: string, name: string) => Promise<unknown>;
    subscribeAuth?: () => Promise<unknown>;
    unsubscribeAuth?: () => Promise<unknown>;
  }>(),
  {
    mode: "anon",
    subscribeAnon: undefined,
    subscribeAuth: undefined,
    unsubscribeAuth: undefined,
  },
);

const email = ref("");
const name = ref("");
const state = ref<SubmitState>("idle");
const subscribed = ref(false);

const emailValid = computed(() => validateEmail(email.value));

async function submit(): Promise<void> {
  if (state.value === "submitting") return;

  if (props.mode === "auth") {
    if (subscribed.value) {
      if (!props.unsubscribeAuth) return;
      state.value = "submitting";
      try {
        await props.unsubscribeAuth();
        subscribed.value = false;
        state.value = "idle";
      } catch {
        state.value = "error";
      }
    } else {
      if (!props.subscribeAuth) return;
      state.value = "submitting";
      try {
        await props.subscribeAuth();
        subscribed.value = true;
        state.value = "done";
      } catch {
        state.value = "error";
      }
    }
  } else {
    if (!emailValid.value || !props.subscribeAnon) return;
    state.value = "submitting";
    try {
      await props.subscribeAnon(email.value.trim(), name.value.trim());
      state.value = "done";
    } catch {
      state.value = "error";
    }
  }
}
</script>

<template>
  <!-- Anonymous mode -->
  <template v-if="mode === 'anon'">
    <div v-if="state !== 'done'" class="sub-form">
      <input
        v-model="name"
        class="sub-input"
        type="text"
        placeholder="Your name (optional)"
        aria-label="Your name (optional)"
        :disabled="state === 'submitting'"
      />
      <input
        v-model="email"
        class="sub-input"
        type="email"
        placeholder="your@email.com"
        aria-label="Email address"
        :disabled="state === 'submitting'"
      />
      <button
        class="sub-btn"
        :disabled="!emailValid || state === 'submitting'"
        @click="submit"
      >
        {{ state === "submitting" ? "Submitting…" : "Subscribe" }}
      </button>
      <p
        v-if="state === 'error'"
        role="alert"
        class="sub-feedback sub-feedback--error"
      >
        Something went wrong — please try again.
      </p>
    </div>
    <div v-else role="status" class="sub-success">
      <span class="sub-success-icon" aria-hidden="true">✓</span>
      <p class="sub-success-text">
        Check your email to confirm your subscription.
      </p>
    </div>
  </template>

  <!-- Auth mode -->
  <div v-else class="sub-auth">
    <template v-if="!subscribed">
      <button
        class="sub-btn"
        :disabled="state === 'submitting'"
        @click="submit"
      >
        {{
          state === "submitting" ? "Subscribing…" : "Subscribe to Blog Updates"
        }}
      </button>
      <p
        v-if="state === 'done'"
        role="status"
        class="sub-feedback sub-feedback--success"
      >
        You're subscribed!
      </p>
    </template>
    <template v-else>
      <span class="sub-subscribed-label">✓ Subscribed to blog updates</span>
      <button
        class="sub-btn sub-btn--unsub"
        :disabled="state === 'submitting'"
        @click="submit"
      >
        {{ state === "submitting" ? "Unsubscribing…" : "Unsubscribe" }}
      </button>
    </template>
    <p
      v-if="state === 'error'"
      role="alert"
      class="sub-feedback sub-feedback--error"
    >
      Something went wrong — please try again.
    </p>
  </div>
</template>

<style lang="scss">
@use "packages/tokens/src/components/subscribe-form";
</style>
