// packages/react-lib/src/components/SectionHeader/SectionHeader.tsx
import { SectionHeaderConfig } from '@m2s2/models';
import './SectionHeader.scss';

interface SectionHeaderProps {
  config: SectionHeaderConfig;
}

export function SectionHeader({ config }: SectionHeaderProps) {
  return (
    <div className="m2s2-section-header">
      <h2 className="sh-label">{config.label}</h2>
      {config.subtitle && <p className="sh-subtitle">{config.subtitle}</p>}
    </div>
  );
}

// packages/vue-lib/src/components/SectionHeader/SectionHeader.vue
<script setup lang="ts">
import type { SectionHeaderConfig } from "@m2s2/models";

defineProps<{ config: SectionHeaderConfig }>();
</script>

<template>
  <div class="m2s2-section-header">
    <h2 class="sh-label">
      {{ config.label }}
    </h2>
    <p v-if="config.subtitle" class="sh-subtitle">
      {{ config.subtitle }}
    </p>
  </div>
</template>

<style lang="scss">
@use "packages/tokens/src/components/section-header";

.m2s2-section-header {
  display: block;
  text-align: center;
  margin-bottom: var(--space-8);
}
</style>
