// packages/react-lib/src/components/cards/FeatureCard/FeatureCard.tsx
import { FeatureCardConfig } from "@m2s2/models";
import { BaseCard } from "../BaseCard/BaseCard";
import "./FeatureCard.scss";

interface FeatureCardProps {
  config: FeatureCardConfig;
}

export function FeatureCard({ config }: FeatureCardProps) {
  return (
    <BaseCard featured={config.featured ?? false}>
      <div className="fc-header">
        {config.icon && (
          <span className="fc-icon" aria-hidden="true">
            {config.icon}
          </span>
        )}
        <h2 className="fc-title">{config.title}</h2>
      </div>
      <p className="fc-body">{config.body}</p>
      {config.items && config.items.length > 0 && (
        <ul className="fc-list">
          {config.items.map((item) => (
            <li key={item}>{item}</li>
          ))}
        </ul>
      )}
      {config.note && <p className="fc-note">{config.note}</p>}
    </BaseCard>
  );
}

// packages/ng-lib/src/lib/components/cards/feature-card/feature-card.component.ts
import { Component, input } from "@angular/core";
import { BaseCardComponent } from "../base-card/base-card.component";
import { FeatureCardConfig } from "../../../models/card/card.model";

@Component({
  selector: "m2s2-feature-card",
  templateUrl: "./feature-card.component.html",
  styleUrls: ["./feature-card.component.scss"],
  standalone: true,
  imports: [BaseCardComponent],
  host: { style: "display: contents" },
})
export class FeatureCardComponent {
  config = input.required<FeatureCardConfig>();
}

<m2s2-card [featured]="config().featured ?? false">
  <div class="fc-header">
    @if (config().icon) {
      <span
        class="fc-icon"
        aria-hidden="true"
        [innerHTML]="config().icon"
      ></span>
    }
    <h2 class="fc-title">{{ config().title }}</h2>
  </div>
  <p class="fc-body">{{ config().body }}</p>
  @if (config().items?.length) {
    <ul class="fc-list">
      @for (item of config().items!; track item) {
        <li>{{ item }}</li>
      }
    </ul>
  }
  @if (config().note) {
    <p class="fc-note">{{ config().note }}</p>
  }
</m2s2-card>
