// packages/vue-lib/src/components/RankedBarChart/RankedBarChart.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from "vue";
import { Chart } from "chart.js/auto";
import type { RankedBarItem } from "@m2s2/models";
import { buildRankedBarChartConfig } from "@m2s2/utils";

const props = defineProps<{ data: RankedBarItem[] }>();

const canvasEl = ref<HTMLCanvasElement>();
let chart: Chart | undefined;

function render() {
  if (!canvasEl.value) return;
  chart?.destroy();
  chart = new Chart(canvasEl.value, buildRankedBarChartConfig(props.data));
}

onMounted(render);
watch(() => props.data, render);
onBeforeUnmount(() => chart?.destroy());
</script>

<template>
  <div class="m2s2-chart">
    <canvas ref="canvasEl" />
  </div>
</template>

<style lang="scss">
.m2s2-chart {
  position: relative;
  width: 100%;
  height: var(--chart-height, 320px);
}
</style>

// packages/react-lib/src/components/RankedBarChart/RankedBarChart.tsx
import { useEffect, useRef } from 'react';
import { Chart } from 'chart.js/auto';
import { RankedBarItem } from '@m2s2/models';
import { buildRankedBarChartConfig } from '@m2s2/utils';
import './RankedBarChart.scss';

interface RankedBarChartProps {
  data: RankedBarItem[];
}

export function RankedBarChart({ data }: RankedBarChartProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    if (!canvasRef.current) return;
    const chart = new Chart(canvasRef.current, buildRankedBarChartConfig(data));
    return () => chart.destroy();
  }, [data]);

  return (
    <div className="m2s2-chart">
      <canvas ref={canvasRef} />
    </div>
  );
}
