// packages/vue-lib/src/components/ThemeProvider/ThemeProvider.vue
<script setup lang="ts">
import { ref, watch, provide, onMounted } from 'vue';
import { THEME_KEY, type Theme } from './useTheme';

const props = withDefaults(defineProps<{
  defaultTheme?: Theme;
}>(), { defaultTheme: 'auto' });

const STORAGE_KEY = 'm2s2-theme';

function readStored(): Theme {
  return (localStorage.getItem(STORAGE_KEY) as Theme | null) ?? props.defaultTheme;
}

function applyTheme(t: Theme) {
  if (t === 'auto') {
    document.documentElement.removeAttribute('data-theme');
  } else {
    document.documentElement.setAttribute('data-theme', t);
  }
}

const theme = ref<Theme>(props.defaultTheme);

onMounted(() => {
  theme.value = readStored();
});

watch(theme, t => {
  localStorage.setItem(STORAGE_KEY, t);
  applyTheme(t);
}, { immediate: false });

function setTheme(t: Theme) {
  theme.value = t;
}

provide(THEME_KEY, { get theme() { return theme.value; }, setTheme });
</script>

<template>
  <slot />
</template>

// packages/react-lib/src/components/ThemeProvider/ThemeProvider.tsx
import { createContext, useCallback, useContext, useEffect, useState } from 'react';

export type Theme = 'dark' | 'light' | 'auto';

interface ThemeContextValue {
  theme: Theme;
  setTheme: (theme: Theme) => void;
}

const ThemeContext = createContext<ThemeContextValue | null>(null);

const STORAGE_KEY = 'm2s2-theme';

function applyTheme(theme: Theme) {
  if (theme === 'auto') {
    document.documentElement.removeAttribute('data-theme');
  } else {
    document.documentElement.setAttribute('data-theme', theme);
  }
}

export function ThemeProvider({ children, defaultTheme = 'auto' }: { children: React.ReactNode; defaultTheme?: Theme }) {
  const [theme, setThemeState] = useState<Theme>(() => {
    return (localStorage.getItem(STORAGE_KEY) as Theme | null) ?? defaultTheme;
  });

  useEffect(() => {
    applyTheme(theme);
  }, [theme]);

  const setTheme = useCallback((next: Theme) => {
    localStorage.setItem(STORAGE_KEY, next);
    setThemeState(next);
  }, []);

  return (
    <ThemeContext.Provider value={{ theme, setTheme }}>
      {children}
    </ThemeContext.Provider>
  );
}

export function useThemeContext(): ThemeContextValue {
  const ctx = useContext(ThemeContext);
  if (!ctx) throw new Error('useTheme must be used within a <ThemeProvider>');
  return ctx;
}
