// packages/ng-lib/src/lib/components/cta-section/cta-section.component.ts
import { Component, input } from "@angular/core";
import { RouterLink } from "@angular/router";
import { CtaConfig } from "../../models/cta/cta.model";

@Component({
  selector: "m2s2-cta-section",
  templateUrl: "./cta-section.component.html",
  styleUrls: ["./cta-section.component.scss"],
  standalone: true,
  imports: [RouterLink],
})
export class CtaSectionComponent {
  readonly config = input.required<CtaConfig>();
}

<section class="m2s2-cta-section">
  <div class="cta-card">
    <div class="cta-text">
      <h2 class="cta-title">{{ config().title }}</h2>
      <p class="cta-body">{{ config().body }}</p>
    </div>
    <a [routerLink]="config().route" class="cta-btn">{{ config().label }}</a>
  </div>
</section>

// packages/react-lib/src/components/CtaSection/CtaSection.tsx
import { CtaConfig } from '@m2s2/models';
import './CtaSection.scss';

interface CtaSectionProps {
  config: CtaConfig;
}

export function CtaSection({ config }: CtaSectionProps) {
  return (
    <section className="m2s2-cta-section">
      <div className="cta-card">
        <div className="cta-text">
          <h2 className="cta-title">{config.title}</h2>
          <p className="cta-body">{config.body}</p>
        </div>
        <a href={config.route} className="cta-btn">
          {config.label}
        </a>
      </div>
    </section>
  );
}
