// packages/react-lib/src/components/BlogEditor/BlogEditor.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import { marked } from "marked";
import type { BlogDraft, BlogPost } from "@m2s2/models";
import {
  BLOG_EDITOR_TOOLBAR,
  calcReadingTime,
  generateSlug,
  todayAsIsoDate,
} from "@m2s2/utils";
import type { ToolbarItem } from "@m2s2/utils";
import "./BlogEditor.scss";

export interface BlogEditorProps {
  /** Populate fields when editing an existing post. */
  initialPost?: BlogPost;
  /** Set to the S3 URL after the platform has uploaded the selected cover image. */
  coverImageUrl?: string;
  /** Existing series to show in the dropdown. Platform fetches these from the blog index. */
  existingSeries?: Array<{ id: string; title: string }>;
  /** Called with the assembled draft when the user clicks Publish. */
  onPublish?: (draft: BlogDraft) => void;
  /** Called with the assembled draft when the user clicks Export. */
  onExportDraft?: (draft: BlogDraft) => void;
  /** Called with the selected File so the platform can upload it to S3. */
  onCoverImageSelected?: (file: File) => void;
}

const NO_SERIES: Array<{ id: string; title: string }> = [];

export function BlogEditor({
  initialPost,
  coverImageUrl,
  existingSeries = NO_SERIES,
  onPublish,
  onExportDraft,
  onCoverImageSelected,
}: BlogEditorProps) {
  const [title, setTitleRaw] = useState(initialPost?.title ?? "");
  const [slug, setSlug] = useState(initialPost?.slug ?? "");
  const [date, setDate] = useState(initialPost?.date ?? todayAsIsoDate());
  const [summary, setSummary] = useState(initialPost?.summary ?? "");
  const [excerpt, setExcerpt] = useState(initialPost?.excerpt ?? "");
  const [tags, setTags] = useState<string[]>(initialPost?.tags ?? []);
  const [readingTime, setReadingTime] = useState(initialPost?.readingTime ?? 1);
  const [content, setContentRaw] = useState(initialPost?.content ?? "");
  const [coverPreview, setCoverPreview] = useState<string | undefined>(
    initialPost?.coverImage,
  );
  const [tagInput, setTagInput] = useState("");
  const [activePane, setActivePane] = useState<"write" | "preview">("write");
  const [selectedSeriesKey, setSelectedSeriesKey] = useState("none");
  const [seriesId, setSeriesId] = useState(initialPost?.series?.id ?? "");
  const [seriesTitle, setSeriesTitle] = useState(
    initialPost?.series?.title ?? "",
  );
  const [seriesPart, setSeriesPart] = useState(initialPost?.series?.part ?? 1);
  const [seriesTotal, setSeriesTotal] = useState<number | undefined>(
    initialPost?.series?.total,
  );

  const slugEdited = useRef(!!initialPost);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Populate all fields when the post changes.
  useEffect(() => {
    if (!initialPost) return;
    setTitleRaw(initialPost.title);
    setSlug(initialPost.slug);
    setDate(initialPost.date);
    setSummary(initialPost.summary);
    setExcerpt(initialPost.excerpt ?? "");
    setTags([...initialPost.tags]);
    setReadingTime(initialPost.readingTime ?? 1);
    setContentRaw(initialPost.content);
    setCoverPreview(initialPost.coverImage);
    setSeriesId(initialPost.series?.id ?? "");
    setSeriesTitle(initialPost.series?.title ?? "");
    setSeriesPart(initialPost.series?.part ?? 1);
    setSeriesTotal(initialPost.series?.total);
    slugEdited.current = true;
  }, [initialPost]);

  // Derive which dropdown item is selected. Re-runs if existingSeries loads after initialPost.
  useEffect(() => {
    if (!initialPost?.series) {
      setSelectedSeriesKey("none");
      return;
    }
    const inList = existingSeries.some((s) => s.id === initialPost.series!.id);
    setSelectedSeriesKey(inList ? initialPost.series!.id : "__new__");
  }, [initialPost, existingSeries]);

  const setTitle = useCallback(
    (value: string) => {
      setTitleRaw(value);
      if (!slugEdited.current) setSlug(generateSlug(value));
      setReadingTime(calcReadingTime(content));
    },
    [content],
  );

  const setContent = useCallback((value: string) => {
    setContentRaw(value);
    setReadingTime(calcReadingTime(value));
  }, []);

  const renderedHtml = marked.parse(content) as string;
  const canPublish =
    title.trim().length > 0 &&
    summary.trim().length > 0 &&
    content.trim().length > 0;

  function onSeriesKeyChange(key: string) {
    setSelectedSeriesKey(key);
    if (key !== "none" && key !== "__new__") {
      const found = existingSeries.find((s) => s.id === key);
      if (found) {
        setSeriesId(found.id);
        setSeriesTitle(found.title);
      }
    }
  }

  function onTagKeyDown(e: React.KeyboardEvent<HTMLInputElement>) {
    if (e.key === "Enter" || e.key === ",") {
      e.preventDefault();
      const tag = generateSlug(tagInput);
      if (tag && !tags.includes(tag)) setTags((prev) => [...prev, tag]);
      setTagInput("");
    }
    if (e.key === "Backspace" && !tagInput && tags.length) {
      setTags((prev) => prev.slice(0, -1));
    }
  }

  function onCoverChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    onCoverImageSelected?.(file);
    const reader = new FileReader();
    reader.onload = () => setCoverPreview(reader.result as string);
    reader.readAsDataURL(file);
  }

  function applyFormat(item: ToolbarItem) {
    const el = textareaRef.current;
    if (!el) return;

    const start = el.selectionStart;
    const end = el.selectionEnd;
    const cur = content;
    let newContent: string;
    let newCursor: number;

    if (item.wrap) {
      const [before, after] = item.wrap;
      const sel = cur.slice(start, end) || "text";
      newContent = cur.slice(0, start) + before + sel + after + cur.slice(end);
      newCursor = start + before.length + sel.length + after.length;
    } else if (item.prefix) {
      const lineStart = cur.lastIndexOf("\n", start - 1) + 1;
      newContent = cur.slice(0, lineStart) + item.prefix + cur.slice(lineStart);
      newCursor = start + item.prefix.length;
    } else if (item.block) {
      newContent = cur.slice(0, start) + item.block + cur.slice(end);
      newCursor = start + item.block.length;
    } else {
      return;
    }

    setContentRaw(newContent);
    setTimeout(() => {
      el.selectionStart = el.selectionEnd = newCursor;
      el.focus();
    }, 0);
  }

  function assembleDraft(): BlogDraft {
    let series: BlogDraft["series"];
    if (selectedSeriesKey === "__new__") {
      const id = seriesId.trim();
      const total = seriesTotal;
      series = id
        ? {
            id,
            title: seriesTitle.trim() || id,
            part: seriesPart,
            ...(total !== undefined ? { total } : {}),
          }
        : undefined;
    } else if (selectedSeriesKey !== "none") {
      const found = existingSeries.find((s) => s.id === selectedSeriesKey);
      const total = seriesTotal;
      series = found
        ? {
            id: found.id,
            title: found.title,
            part: seriesPart,
            ...(total !== undefined ? { total } : {}),
          }
        : undefined;
    }
    return {
      title,
      slug: slug || generateSlug(title),
      date,
      summary,
      excerpt: excerpt || undefined,
      tags,
      readingTime,
      content,
      coverImage: coverImageUrl ?? coverPreview,
      series,
    };
  }

  function handlePublish() {
    if (!canPublish) return;
    onPublish?.(assembleDraft());
  }

  function handleExport() {
    if (!canPublish) return;
    onExportDraft?.(assembleDraft());
  }

  const previewUrl = coverPreview ?? coverImageUrl;

  return (
    <div className="be-root">
      {/* ── Metadata ────────────────────────────────────────────────────── */}
      <section className="be-meta">
        <div className="be-field be-field--full">
          <label className="be-label">
            Title <span className="be-required">*</span>
          </label>
          <input
            className="be-input"
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Post title…"
          />
        </div>

        <div className="be-field">
          <label className="be-label">Slug</label>
          <input
            className="be-input"
            type="text"
            value={slug}
            onChange={(e) => {
              setSlug(e.target.value);
              slugEdited.current = true;
            }}
            placeholder="post-slug"
          />
        </div>

        <div className="be-field">
          <label className="be-label" htmlFor="be-date">
            Date
          </label>
          <input
            id="be-date"
            className="be-input be-input--date"
            type="date"
            value={date}
            onChange={(e) => setDate(e.target.value)}
          />
        </div>

        <div className="be-field be-field--full">
          <label className="be-label">
            Summary <span className="be-required">*</span>
          </label>
          <textarea
            className="be-input be-input--textarea"
            rows={2}
            value={summary}
            onChange={(e) => setSummary(e.target.value)}
            placeholder="Short description shown in blog listings…"
          />
        </div>

        <div className="be-field be-field--full">
          <label className="be-label">
            Excerpt <span className="be-optional">(optional)</span>
          </label>
          <textarea
            className="be-input be-input--textarea"
            rows={2}
            value={excerpt}
            onChange={(e) => setExcerpt(e.target.value)}
            placeholder="Longer teaser for social previews…"
          />
        </div>

        <div className="be-field">
          <label className="be-label">Tags</label>
          <div className="be-tags">
            {tags.map((tag) => (
              <span key={tag} className="be-tag">
                {tag}
                <button
                  type="button"
                  className="be-tag__remove"
                  onClick={() =>
                    setTags((prev) => prev.filter((t) => t !== tag))
                  }
                  aria-label={`Remove tag ${tag}`}
                >
                  ×
                </button>
              </span>
            ))}
            <input
              className="be-tag-input"
              type="text"
              value={tagInput}
              onChange={(e) => setTagInput(e.target.value)}
              onKeyDown={onTagKeyDown}
              placeholder="Add tag, press Enter…"
            />
          </div>
        </div>

        <div className="be-field">
          <label className="be-label" htmlFor="be-reading-time">
            Reading time (min)
          </label>
          <input
            id="be-reading-time"
            className="be-input be-input--narrow"
            type="number"
            min={1}
            value={readingTime}
            onChange={(e) => setReadingTime(Number(e.target.value))}
          />
        </div>

        <div className="be-field be-field--cover">
          <label className="be-label">Cover Image</label>
          <div className="be-cover">
            {previewUrl && (
              <img
                className="be-cover__preview"
                src={previewUrl}
                alt="Cover preview"
              />
            )}
            <label className="be-cover__pick">
              {previewUrl ? "Replace" : "Choose image"}
              <input
                type="file"
                accept="image/*"
                onChange={onCoverChange}
                hidden
              />
            </label>
          </div>
        </div>

        <div className="be-field-group-label">
          Series <span className="be-optional">(optional)</span>
        </div>

        <div className="be-field be-field--full">
          <label className="be-label" htmlFor="be-series">
            Series
          </label>
          <select
            id="be-series"
            className="be-input be-input--select"
            value={selectedSeriesKey}
            onChange={(e) => onSeriesKeyChange(e.target.value)}
          >
            <option value="none">— None —</option>
            {existingSeries.map((s) => (
              <option key={s.id} value={s.id}>
                {s.title}
              </option>
            ))}
            <option value="__new__">+ New series…</option>
          </select>
        </div>

        {selectedSeriesKey === "__new__" && (
          <>
            <div className="be-field">
              <label className="be-label">Series ID</label>
              <input
                className="be-input"
                type="text"
                value={seriesId}
                onChange={(e) => setSeriesId(e.target.value)}
                placeholder="e.g. go-backend"
              />
            </div>
            <div className="be-field">
              <label className="be-label">Series Title</label>
              <input
                className="be-input"
                type="text"
                value={seriesTitle}
                onChange={(e) => setSeriesTitle(e.target.value)}
                placeholder="e.g. Go Backend Series"
              />
            </div>
          </>
        )}

        {selectedSeriesKey !== "none" && (
          <div className="be-field be-field--narrow-pair">
            <div>
              <label className="be-label" htmlFor="series-part">
                Part
              </label>
              <input
                id="series-part"
                className="be-input be-input--narrow"
                type="number"
                min={1}
                value={seriesPart}
                onChange={(e) => setSeriesPart(Number(e.target.value))}
              />
            </div>
            <div>
              <label className="be-label" htmlFor="series-total">
                Total Parts <span className="be-optional">(optional)</span>
              </label>
              <input
                id="series-total"
                className="be-input be-input--narrow"
                type="number"
                min={1}
                value={seriesTotal ?? ""}
                placeholder="auto"
                onChange={(e) =>
                  setSeriesTotal(
                    e.target.value ? Number(e.target.value) : undefined,
                  )
                }
              />
              <span className="be-hint">
                Leave blank to derive from published post count
              </span>
            </div>
          </div>
        )}
      </section>

      {/* ── Editor ──────────────────────────────────────────────────────── */}
      <section className="be-editor">
        <div className="be-toolbar" role="toolbar" aria-label="Formatting">
          {/* Mobile pane toggle — hidden on desktop via CSS */}
          <div className="be-pane-toggle" role="group" aria-label="Editor mode">
            <button
              type="button"
              className={`be-pane-toggle__btn${activePane === "write" ? " be-pane-toggle__btn--active" : ""}`}
              onClick={() => setActivePane("write")}
            >
              Write
            </button>
            <button
              type="button"
              className={`be-pane-toggle__btn${activePane === "preview" ? " be-pane-toggle__btn--active" : ""}`}
              onClick={() => setActivePane("preview")}
            >
              Preview
            </button>
          </div>

          <div className="be-toolbar__tools">
            {BLOG_EDITOR_TOOLBAR.map((item) => (
              <button
                key={item.label}
                type="button"
                className="be-toolbar__btn"
                title={item.label}
                aria-label={item.label}
                onClick={() => applyFormat(item)}
              >
                {item.icon}
              </button>
            ))}
          </div>
        </div>

        <div className="be-panes">
          <div
            className={`be-pane be-pane--write${activePane === "preview" ? " be-pane--hidden" : ""}`}
          >
            <div className="be-pane__label">Markdown</div>
            <textarea
              ref={textareaRef}
              className="be-pane__textarea"
              value={content}
              onChange={(e) => setContent(e.target.value)}
              placeholder="Write your post in markdown…"
              spellCheck
            />
          </div>

          <div
            className={`be-pane be-pane--preview${activePane === "write" ? " be-pane--hidden" : ""}`}
          >
            <div className="be-pane__label">Preview</div>
            {/* content is authored by the admin user — trusted HTML */}
            <div
              className="be-pane__preview prose"
              dangerouslySetInnerHTML={{ __html: renderedHtml }}
            />
          </div>
        </div>
      </section>

      {/* ── Footer ──────────────────────────────────────────────────────── */}
      <footer className="be-footer">
        <span className="be-footer__meta">~{readingTime} min read</span>
        <div className="be-footer__actions">
          <button
            type="button"
            className="be-export"
            disabled={!canPublish}
            onClick={handleExport}
          >
            Export
          </button>
          <button
            type="button"
            className="be-publish"
            disabled={!canPublish}
            onClick={handlePublish}
          >
            Publish Post
          </button>
        </div>
      </footer>
    </div>
  );
}

// packages/vue-lib/src/components/BlogEditor/BlogEditor.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { marked } from "marked";
import type { BlogDraft, BlogPost } from "@m2s2/models";
import {
  BLOG_EDITOR_TOOLBAR,
  calcReadingTime,
  generateSlug,
  todayAsIsoDate,
} from "@m2s2/utils";
import type { ToolbarItem } from "@m2s2/utils";

const props = withDefaults(
  defineProps<{
    /** Populate fields when editing an existing post. */
    initialPost?: BlogPost;
    /** Set to the S3 URL after the platform has uploaded the selected cover image. */
    coverImageUrl?: string;
    /** Existing series to show in the dropdown. Platform fetches these from the blog index. */
    existingSeries?: Array<{ id: string; title: string }>;
  }>(),
  {
    initialPost: undefined,
    coverImageUrl: undefined,
    existingSeries: () => [],
  },
);

const emit = defineEmits<{
  /** Emits the assembled draft when the user clicks Publish. */
  publish: [draft: BlogDraft];
  /** Emits the assembled draft when the user clicks Export. */
  exportDraft: [draft: BlogDraft];
  /** Emits the selected File so the platform can upload it to S3. */
  coverImageSelected: [file: File];
}>();

const title = ref(props.initialPost?.title ?? "");
const slug = ref(props.initialPost?.slug ?? "");
const date = ref(props.initialPost?.date ?? todayAsIsoDate());
const summary = ref(props.initialPost?.summary ?? "");
const excerpt = ref(props.initialPost?.excerpt ?? "");
const tags = ref<string[]>([...(props.initialPost?.tags ?? [])]);
const readingTime = ref(props.initialPost?.readingTime ?? 1);
const content = ref(props.initialPost?.content ?? "");
const coverPreview = ref<string | undefined>(props.initialPost?.coverImage);
const tagInput = ref("");
const activePane = ref<"write" | "preview">("write");
const slugEdited = ref(!!props.initialPost);
const textareaEl = ref<HTMLTextAreaElement | null>(null);
const selectedSeriesKey = ref("none");
const seriesId = ref(props.initialPost?.series?.id ?? "");
const seriesTitle = ref(props.initialPost?.series?.title ?? "");
const seriesPart = ref(props.initialPost?.series?.part ?? 1);
const seriesTotal = ref<number | undefined>(props.initialPost?.series?.total);

// Populate all fields when the post changes.
watch(
  () => props.initialPost,
  (post) => {
    if (!post) return;
    title.value = post.title;
    slug.value = post.slug;
    date.value = post.date;
    summary.value = post.summary;
    excerpt.value = post.excerpt ?? "";
    tags.value = [...post.tags];
    readingTime.value = post.readingTime ?? 1;
    content.value = post.content;
    coverPreview.value = post.coverImage;
    seriesId.value = post.series?.id ?? "";
    seriesTitle.value = post.series?.title ?? "";
    seriesPart.value = post.series?.part ?? 1;
    seriesTotal.value = post.series?.total;
    slugEdited.value = true;
  },
);

// Derive which dropdown item is selected. Re-runs if existingSeries loads after initialPost.
watch(
  [() => props.initialPost, () => props.existingSeries],
  ([post, existing]) => {
    if (!post?.series) {
      selectedSeriesKey.value = "none";
      return;
    }
    const inList = existing.some(
      (s: { id: string }) => s.id === post.series!.id,
    );
    selectedSeriesKey.value = inList ? post.series!.id : "__new__";
  },
);

const renderedHtml = computed(() => marked.parse(content.value) as string);
const canPublish = computed(
  () =>
    title.value.trim().length > 0 &&
    summary.value.trim().length > 0 &&
    content.value.trim().length > 0,
);
const previewUrl = computed(() => coverPreview.value ?? props.coverImageUrl);

function onSeriesKeyChange(e: Event) {
  const key = (e.target as HTMLSelectElement).value;
  selectedSeriesKey.value = key;
  if (key !== "none" && key !== "__new__") {
    const found = props.existingSeries.find((s) => s.id === key);
    if (found) {
      seriesId.value = found.id;
      seriesTitle.value = found.title;
    }
  }
}

function onTitleChange(e: Event) {
  title.value = (e.target as HTMLInputElement).value;
  if (!slugEdited.value) slug.value = generateSlug(title.value);
  readingTime.value = calcReadingTime(content.value);
}

function onContentChange(e: Event) {
  content.value = (e.target as HTMLTextAreaElement).value;
  readingTime.value = calcReadingTime(content.value);
}

function onTagKeydown(e: KeyboardEvent) {
  if (e.key === "Enter" || e.key === ",") {
    e.preventDefault();
    const tag = generateSlug(tagInput.value);
    if (tag && !tags.value.includes(tag)) tags.value = [...tags.value, tag];
    tagInput.value = "";
  }
  if (e.key === "Backspace" && !tagInput.value && tags.value.length) {
    tags.value = tags.value.slice(0, -1);
  }
}

function removeTag(tag: string) {
  tags.value = tags.value.filter((t) => t !== tag);
}

function onCoverChange(e: Event) {
  const file = (e.target as HTMLInputElement).files?.[0];
  if (!file) return;
  emit("coverImageSelected", file);
  const reader = new FileReader();
  reader.onload = () => {
    coverPreview.value = reader.result as string;
  };
  reader.readAsDataURL(file);
}

function applyFormat(item: ToolbarItem) {
  const el = textareaEl.value;
  if (!el) return;

  const start = el.selectionStart;
  const end = el.selectionEnd;
  const cur = content.value;
  let newContent: string;
  let newCursor: number;

  if (item.wrap) {
    const [before, after] = item.wrap;
    const sel = cur.slice(start, end) || "text";
    newContent = cur.slice(0, start) + before + sel + after + cur.slice(end);
    newCursor = start + before.length + sel.length + after.length;
  } else if (item.prefix) {
    const lineStart = cur.lastIndexOf("\n", start - 1) + 1;
    newContent = cur.slice(0, lineStart) + item.prefix + cur.slice(lineStart);
    newCursor = start + item.prefix.length;
  } else if (item.block) {
    newContent = cur.slice(0, start) + item.block + cur.slice(end);
    newCursor = start + item.block.length;
  } else {
    return;
  }

  content.value = newContent;
  setTimeout(() => {
    el.selectionStart = el.selectionEnd = newCursor;
    el.focus();
  }, 0);
}

function assembleDraft(): BlogDraft {
  let series: BlogDraft["series"];
  const total = seriesTotal.value;
  if (selectedSeriesKey.value === "__new__") {
    const id = seriesId.value.trim();
    series = id
      ? {
          id,
          title: seriesTitle.value.trim() || id,
          part: seriesPart.value,
          ...(total !== undefined ? { total } : {}),
        }
      : undefined;
  } else if (selectedSeriesKey.value !== "none") {
    const found = props.existingSeries.find(
      (s) => s.id === selectedSeriesKey.value,
    );
    series = found
      ? {
          id: found.id,
          title: found.title,
          part: seriesPart.value,
          ...(total !== undefined ? { total } : {}),
        }
      : undefined;
  }
  return {
    title: title.value,
    slug: slug.value || generateSlug(title.value),
    date: date.value,
    summary: summary.value,
    excerpt: excerpt.value || undefined,
    tags: tags.value,
    readingTime: readingTime.value,
    content: content.value,
    coverImage: props.coverImageUrl ?? coverPreview.value,
    series,
  };
}

function onPublish() {
  if (!canPublish.value) return;
  emit("publish", assembleDraft());
}

function onExport() {
  if (!canPublish.value) return;
  emit("exportDraft", assembleDraft());
}
</script>

<template>
  <div class="be-root">
    <!-- ── Metadata ──────────────────────────────────────────────────────── -->
    <section class="be-meta">
      <div class="be-field be-field--full">
        <label class="be-label">Title <span class="be-required">*</span></label>
        <input
          class="be-input"
          type="text"
          :value="title"
          placeholder="Post title…"
          @input="onTitleChange"
        />
      </div>

      <div class="be-field">
        <label class="be-label">Slug</label>
        <input
          v-model="slug"
          class="be-input"
          type="text"
          placeholder="post-slug"
          @input="slugEdited = true"
        />
      </div>

      <div class="be-field">
        <label class="be-label" for="be-date">Date</label>
        <input
          id="be-date"
          v-model="date"
          class="be-input be-input--date"
          type="date"
        />
      </div>

      <div class="be-field be-field--full">
        <label class="be-label"
          >Summary <span class="be-required">*</span></label
        >
        <textarea
          v-model="summary"
          class="be-input be-input--textarea"
          rows="2"
          placeholder="Short description shown in blog listings…"
        />
      </div>

      <div class="be-field be-field--full">
        <label class="be-label"
          >Excerpt <span class="be-optional">(optional)</span></label
        >
        <textarea
          v-model="excerpt"
          class="be-input be-input--textarea"
          rows="2"
          placeholder="Longer teaser for social previews…"
        />
      </div>

      <div class="be-field">
        <label class="be-label">Tags</label>
        <div class="be-tags">
          <span v-for="tag in tags" :key="tag" class="be-tag">
            {{ tag }}
            <button
              type="button"
              class="be-tag__remove"
              :aria-label="`Remove tag ${tag}`"
              @click="removeTag(tag)"
            >
              ×
            </button>
          </span>
          <input
            v-model="tagInput"
            class="be-tag-input"
            type="text"
            placeholder="Add tag, press Enter…"
            @keydown="onTagKeydown"
          />
        </div>
      </div>

      <div class="be-field">
        <label class="be-label" for="be-reading-time">Reading time (min)</label>
        <input
          id="be-reading-time"
          v-model.number="readingTime"
          class="be-input be-input--narrow"
          type="number"
          min="1"
        />
      </div>

      <div class="be-field be-field--cover">
        <label class="be-label">Cover Image</label>
        <div class="be-cover">
          <img
            v-if="previewUrl"
            class="be-cover__preview"
            :src="previewUrl"
            alt="Cover preview"
          />
          <label class="be-cover__pick">
            {{ previewUrl ? "Replace" : "Choose image" }}
            <input
              type="file"
              accept="image/*"
              hidden
              @change="onCoverChange"
            />
          </label>
        </div>
      </div>

      <div class="be-field-group-label">
        Series <span class="be-optional">(optional)</span>
      </div>

      <div class="be-field be-field--full">
        <label class="be-label" for="be-series">Series</label>
        <select
          id="be-series"
          class="be-input be-input--select"
          :value="selectedSeriesKey"
          @change="onSeriesKeyChange"
        >
          <option value="none">— None —</option>
          <option v-for="s in existingSeries" :key="s.id" :value="s.id">
            {{ s.title }}
          </option>
          <option value="__new__">+ New series…</option>
        </select>
      </div>

      <template v-if="selectedSeriesKey === '__new__'">
        <div class="be-field">
          <label class="be-label">Series ID</label>
          <input
            v-model="seriesId"
            class="be-input"
            type="text"
            placeholder="e.g. go-backend"
          />
        </div>
        <div class="be-field">
          <label class="be-label">Series Title</label>
          <input
            v-model="seriesTitle"
            class="be-input"
            type="text"
            placeholder="e.g. Go Backend Series"
          />
        </div>
      </template>

      <div
        v-if="selectedSeriesKey !== 'none'"
        class="be-field be-field--narrow-pair"
      >
        <div>
          <label class="be-label">Part</label>
          <input
            v-model.number="seriesPart"
            class="be-input be-input--narrow"
            type="number"
            min="1"
          />
        </div>
        <div>
          <label class="be-label"
            >Total Parts <span class="be-optional">(optional)</span></label
          >
          <input
            class="be-input be-input--narrow"
            type="number"
            min="1"
            :value="seriesTotal"
            placeholder="auto"
            @input="
              seriesTotal = ($event.target as HTMLInputElement).value
                ? +($event.target as HTMLInputElement).value
                : undefined
            "
          />
          <span class="be-hint"
            >Leave blank to derive from published post count</span
          >
        </div>
      </div>
    </section>

    <!-- ── Editor ────────────────────────────────────────────────────────── -->
    <section class="be-editor">
      <div class="be-toolbar" role="toolbar" aria-label="Formatting">
        <!-- Mobile pane toggle — hidden on desktop via CSS -->
        <div class="be-pane-toggle" role="group" aria-label="Editor mode">
          <button
            type="button"
            class="be-pane-toggle__btn"
            :class="{ 'be-pane-toggle__btn--active': activePane === 'write' }"
            @click="activePane = 'write'"
          >
            Write
          </button>
          <button
            type="button"
            class="be-pane-toggle__btn"
            :class="{
              'be-pane-toggle__btn--active': activePane === 'preview',
            }"
            @click="activePane = 'preview'"
          >
            Preview
          </button>
        </div>

        <div class="be-toolbar__tools">
          <button
            v-for="item in BLOG_EDITOR_TOOLBAR"
            :key="item.label"
            type="button"
            class="be-toolbar__btn"
            :title="item.label"
            :aria-label="item.label"
            @click="applyFormat(item)"
          >
            {{ item.icon }}
          </button>
        </div>
      </div>

      <div class="be-panes">
        <div
          class="be-pane be-pane--write"
          :class="{ 'be-pane--hidden': activePane === 'preview' }"
        >
          <div class="be-pane__label">Markdown</div>
          <textarea
            ref="textareaEl"
            class="be-pane__textarea"
            :value="content"
            placeholder="Write your post in markdown…"
            spellcheck="true"
            @input="onContentChange"
          />
        </div>

        <div
          class="be-pane be-pane--preview"
          :class="{ 'be-pane--hidden': activePane === 'write' }"
        >
          <div class="be-pane__label">Preview</div>
          <!-- content is authored by the admin user — trusted HTML -->
          <!-- eslint-disable-next-line vue/no-v-html -->
          <div class="be-pane__preview prose" v-html="renderedHtml" />
        </div>
      </div>
    </section>

    <!-- ── Footer ────────────────────────────────────────────────────────── -->
    <footer class="be-footer">
      <span class="be-footer__meta">~{{ readingTime }} min read</span>
      <div class="be-footer__actions">
        <button
          type="button"
          class="be-export"
          :disabled="!canPublish"
          @click="onExport"
        >
          Export
        </button>
        <button
          type="button"
          class="be-publish"
          :disabled="!canPublish"
          @click="onPublish"
        >
          Publish Post
        </button>
      </div>
    </footer>
  </div>
</template>

<style lang="scss">
@use "packages/tokens/src/components/blog-editor";
</style>
