// packages/ng-lib/src/lib/components/cards/blog-card/blog-card.component.ts
import { Component, input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { BlogCardConfig } from '../../../models/card/card.model';

@Component({
  selector: 'm2s2-blog-card',
  templateUrl: './blog-card.component.html',
  styleUrls: ['./blog-card.component.scss'],
  standalone: true,
  imports: [RouterLink],
})
export class BlogCardComponent {
  config = input.required<BlogCardConfig>();

  formatDate(iso: string): string {
    return new Date(iso).toLocaleDateString('en-US', {
      year: 'numeric', month: 'long', day: 'numeric',
    });
  }
}

<div class="bc-cover">
  @if (config().coverImage) {
    <img [src]="config().coverImage" [alt]="config().title" class="bc-cover-img" loading="lazy" />
  } @else {
    <div class="bc-cover-placeholder">
      <span class="bc-cover-tag">{{ config().tags[0] }}</span>
    </div>
  }
</div>

<div class="bc-inner">
  <div class="bc-meta">
    <time [dateTime]="config().date">{{ formatDate(config().date) }}</time>
  </div>
  <h2 class="bc-title">
    <a [routerLink]="['/blog', config().slug]">{{ config().title }}</a>
  </h2>
  <p class="bc-summary">{{ config().summary }}</p>
  <div class="bc-tags">
    @for (tag of config().tags; track tag) {
      <span class="bc-tag">{{ tag }}</span>
    }
  </div>
</div>

// packages/react-lib/src/components/cards/BlogCard/BlogCard.tsx
import { Link } from 'react-router';
import { BlogCardConfig } from '@m2s2/models';
import './BlogCard.scss';

interface BlogCardProps {
  config: BlogCardConfig;
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
}

export function BlogCard({ config }: BlogCardProps) {
  return (
    <div className="m2s2-blog-card">
      <div className="bc-cover">
        {config.coverImage ? (
          <img src={config.coverImage} alt={config.title} className="bc-cover-img" loading="lazy" />
        ) : (
          <div className="bc-cover-placeholder">
            <span className="bc-cover-tag">{config.tags[0]}</span>
          </div>
        )}
      </div>
      <div className="bc-inner">
        <div className="bc-meta">
          <time dateTime={config.date}>{formatDate(config.date)}</time>
        </div>
        <h2 className="bc-title">
          <Link to={`/blog/${config.slug}`}>{config.title}</Link>
        </h2>
        <p className="bc-summary">{config.summary}</p>
        <div className="bc-tags">
          {config.tags.map((tag) => (
            <span key={tag} className="bc-tag">{tag}</span>
          ))}
        </div>
      </div>
    </div>
  );
}
