// packages/ng-lib/src/lib/components/status-row-list/status-row-list.component.ts
import { Component, input } from "@angular/core";
import { StatusBadgeComponent } from "../status-badge/status-badge.component";
import { StatusRowItem } from "../../models/status-row-list/status-row-list.model";

@Component({
  selector: "m2s2-status-row-list",
  templateUrl: "./status-row-list.component.html",
  styleUrls: ["./status-row-list.component.scss"],
  standalone: true,
  imports: [StatusBadgeComponent],
})
export class StatusRowListComponent {
  rows = input.required<StatusRowItem[]>();
}

<ul class="srl-list">
  @for (row of rows(); track row.id) {
    <li class="srl-row">
      <div class="srl-main">
        <span class="srl-label">{{ row.label }}</span>
        <m2s2-status-badge [status]="row.status" />
      </div>
      @if (row.detail) {
        <p class="srl-detail">{{ row.detail }}</p>
      }
      @if (row.link) {
        <a
          class="srl-link"
          [href]="row.link.href"
          target="_blank"
          rel="noopener noreferrer"
          >{{ row.link.label }}</a
        >
      }
    </li>
  }
</ul>

// packages/react-lib/src/components/StatusRowList/StatusRowList.tsx
import { StatusRowItem } from "@m2s2/models";
import { StatusBadge } from "../StatusBadge/StatusBadge";
import "./StatusRowList.scss";

interface StatusRowListProps {
  rows: StatusRowItem[];
}

export function StatusRowList({ rows }: StatusRowListProps) {
  return (
    <ul className="srl-list">
      {rows.map((row) => (
        <li className="srl-row" key={row.id}>
          <div className="srl-main">
            <span className="srl-label">{row.label}</span>
            <StatusBadge status={row.status} />
          </div>
          {row.detail && <p className="srl-detail">{row.detail}</p>}
          {row.link && (
            <a
              className="srl-link"
              href={row.link.href}
              target="_blank"
              rel="noopener noreferrer"
            >
              {row.link.label}
            </a>
          )}
        </li>
      ))}
    </ul>
  );
}
