// packages/ng-lib/src/lib/components/stat-row/stat-row.component.ts
import { Component, input } from "@angular/core";
import { StatItem } from "../../models/stat-row/stat-row.model";

@Component({
  selector: "m2s2-stat-row",
  templateUrl: "./stat-row.component.html",
  styleUrls: ["./stat-row.component.scss"],
  standalone: true,
})
export class StatRowComponent {
  stats = input.required<StatItem[]>();
}

<div class="sr-row">
  @for (stat of stats(); track stat.label; let last = $last) {
    <div class="sr-item">
      <span class="sr-value">{{ stat.value }}</span>
      <span class="sr-label">{{ stat.label }}</span>
    </div>
    @if (!last) {
      <div class="sr-divider" aria-hidden="true"></div>
    }
  }
</div>

// packages/react-lib/src/components/StatRow/StatRow.tsx
import { Fragment } from "react";
import { StatItem } from "@m2s2/models";
import "./StatRow.scss";

interface StatRowProps {
  stats: StatItem[];
}

export function StatRow({ stats }: StatRowProps) {
  return (
    <div className="sr-row">
      {stats.map((stat, i) => (
        <Fragment key={stat.label}>
          <div className="sr-item">
            <span className="sr-value">{stat.value}</span>
            <span className="sr-label">{stat.label}</span>
          </div>
          {i < stats.length - 1 && (
            <div className="sr-divider" aria-hidden="true" />
          )}
        </Fragment>
      ))}
    </div>
  );
}
