// packages/ng-lib/src/lib/components/status-badge/status-badge.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from "@angular/core";
import {
  STATUS_LABELS,
  StatusBadgeVariant,
} from "../../models/status-badge/status-badge.model";

@Component({
  selector: "m2s2-status-badge",
  template: `{{ displayLabel() }}`,
  styleUrls: ["./status-badge.component.scss"],
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    role: "status",
    "[attr.data-status]": "status()",
    "[attr.data-variant]": "variant()",
  },
})
export class StatusBadgeComponent {
  status = input.required<string>();
  label = input<string | undefined>(undefined);
  variant = input<StatusBadgeVariant>("badge");

  displayLabel = computed(
    () => this.label() ?? STATUS_LABELS[this.status()] ?? this.status(),
  );
}

// packages/react-lib/src/components/StatusBadge/StatusBadge.tsx
import { STATUS_LABELS, StatusBadgeVariant } from "@m2s2/models";
import "./StatusBadge.scss";

interface StatusBadgeProps {
  status: string;
  label?: string;
  variant?: StatusBadgeVariant;
}

export function StatusBadge({
  status,
  label,
  variant = "badge",
}: StatusBadgeProps) {
  const displayLabel = label ?? STATUS_LABELS[status] ?? status;
  return (
    <span
      role="status"
      className="m2s2-status-badge"
      data-status={status}
      data-variant={variant}
    >
      {displayLabel}
    </span>
  );
}
