// packages/react-lib/src/components/DataTable/DataTable.tsx
import { useEffect, useRef, useState } from 'react';
import type { ColumnDef } from '@m2s2/models';
import { getStatusLabel } from '@m2s2/utils';
import './DataTable.scss';

interface DataTableProps {
  children: React.ReactNode;
  columnDefs?: ColumnDef[];
  colVisibility?: Record<string, boolean>;
  statuses?: string[];
  statusFilter?: string;
  statusLabels?: Record<string, string>;
  searchValue?: string;
  searchPlaceholder?: string;
  totalCount?: number;
  filteredCount?: number;
  emptyMessage?: string;
  onSearchChange?: (value: string) => void;
  onStatusChange?: (status: string) => void;
  onColToggle?: (key: string) => void;
}

export function DataTable({
  children,
  columnDefs = [],
  colVisibility = {},
  statuses = [],
  statusFilter = 'all',
  statusLabels = {},
  searchValue = '',
  searchPlaceholder = 'Search…',
  totalCount = 0,
  filteredCount = 0,
  emptyMessage = 'No data yet.',
  onSearchChange,
  onStatusChange,
  onColToggle,
}: DataTableProps) {
  const [showCols, setShowCols] = useState(false);
  const colWrapRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!showCols) return;
    function handleClick(e: MouseEvent) {
      if (!colWrapRef.current?.contains(e.target as Node)) {
        setShowCols(false);
      }
    }
    document.addEventListener('click', handleClick);
    return () => document.removeEventListener('click', handleClick);
  }, [showCols]);

  if (totalCount === 0) {
    return (
      <div className="table-panel">
        <p className="dt-empty">{emptyMessage}</p>
      </div>
    );
  }

  return (
    <div className="table-panel">
      <div className="dt-toolbar">
        {statuses.length > 0 && (
          <>
            <input
              className="dt-search"
              type="search"
              placeholder={searchPlaceholder}
              aria-label="Search"
              value={searchValue}
              onChange={e => onSearchChange?.(e.target.value)}
            />
            <div className="dt-pills" role="group" aria-label="Filter by status">
              {statuses.map(s => (
                <button
                  key={s}
                  className={`dt-pill${statusFilter === s ? ' dt-pill--active' : ''}`}
                  onClick={() => onStatusChange?.(s)}
                >
                  {getStatusLabel(s, statusLabels)}
                </button>
              ))}
            </div>
            <span className="dt-count">{filteredCount} of {totalCount}</span>
          </>
        )}

        {columnDefs.length > 0 && (
          <div className="dt-col-wrap" ref={colWrapRef}>
            <button
              className="dt-col-btn"
              aria-expanded={showCols}
              aria-controls="dt-col-panel"
              onClick={() => setShowCols(v => !v)}
            >
              ⚙ Columns
            </button>
            {showCols && (
              <div id="dt-col-panel" className="dt-col-panel">
                {columnDefs.map(col => (
                  <label key={col.key} className="dt-col-check">
                    <input
                      type="checkbox"
                      checked={colVisibility[col.key] ?? true}
                      onChange={() => onColToggle?.(col.key)}
                    />
                    {col.label}
                  </label>
                ))}
              </div>
            )}
          </div>
        )}
      </div>

      <div className="dt-scroll">{children}</div>
    </div>
  );
}

// packages/ng-lib/src/lib/components/data-table/data-table.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  ElementRef,
  HostListener,
  ViewChild,
  input,
  output,
  signal,
} from "@angular/core";
import { getStatusLabel as resolveStatusLabel } from "@m2s2/utils";
import type { ColumnDef } from "../../models/data-table/data-table.model";

@Component({
  selector: "m2s2-data-table",
  templateUrl: "./data-table.component.html",
  styleUrls: ["./data-table.component.scss"],
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [],
})
export class DataTableComponent {
  @ViewChild("colWrap") private colWrap?: ElementRef;

  @HostListener("document:click", ["$event"])
  onDocumentClick(event: Event): void {
    if (!this.colWrap?.nativeElement.contains(event.target)) {
      this.showCols.set(false);
    }
  }
  searchValue = input<string>("");
  searchPlaceholder = input<string>("Search…");
  statuses = input<string[]>([]);
  statusFilter = input<string>("all");
  statusLabels = input<Record<string, string>>({});
  columnDefs = input<ColumnDef[]>([]);
  colVisibility = input<Record<string, boolean>>({});
  totalCount = input<number>(0);
  filteredCount = input<number>(0);
  emptyMessage = input<string>("No data yet.");

  searchChange = output<string>();
  statusChange = output<string>();
  colToggle = output<string>();

  readonly showCols = signal(false);

  getStatusLabel(s: string): string {
    return resolveStatusLabel(s, this.statusLabels());
  }
}

<div class="table-panel">
  @if (totalCount() === 0) {
    <p class="dt-empty">{{ emptyMessage() }}</p>
  } @else {
    <div class="dt-toolbar">
      <!-- Search + status pills -->
      @if (statuses().length > 0) {
        <input
          class="dt-search"
          type="search"
          [placeholder]="searchPlaceholder()"
          aria-label="Search"
          [value]="searchValue()"
          (input)="searchChange.emit($any($event.target).value)"
        />
        <div class="dt-pills" role="group" aria-label="Filter by status">
          @for (s of statuses(); track s) {
            <button
              class="dt-pill"
              [class.dt-pill--active]="statusFilter() === s"
              (click)="statusChange.emit(s)"
            >
              {{ getStatusLabel(s) }}
            </button>
          }
        </div>
        <span class="dt-count"
          >{{ filteredCount() }} of {{ totalCount() }}</span
        >
      }

      <!-- Column toggle — pushed to the right -->
      @if (columnDefs().length > 0) {
        <div class="dt-col-wrap" #colWrap>
          <button
            class="dt-col-btn"
            [attr.aria-expanded]="showCols()"
            aria-controls="dt-col-panel"
            (click)="showCols.set(!showCols())"
          >
            &#9881; Columns
          </button>
          @if (showCols()) {
            <div id="dt-col-panel" class="dt-col-panel">
              @for (col of columnDefs(); track col.key) {
                <label class="dt-col-check">
                  <input
                    type="checkbox"
                    [checked]="colVisibility()[col.key]"
                    (change)="colToggle.emit(col.key)"
                  />
                  {{ col.label }}
                </label>
              }
            </div>
          }
        </div>
      }
    </div>

    <div class="dt-scroll">
      <ng-content />
    </div>
  }
</div>
