// packages/react-lib/src/components/Toast/Toast.tsx
import { ReactNode } from "react";
import { ToastKind } from "@m2s2/models";
import "./Toast.scss";

interface ToastProps {
  kind?: ToastKind;
  onDismiss: () => void;
  children: ReactNode;
}

export function Toast({ kind = "info", onDismiss, children }: ToastProps) {
  return (
    <div
      className="m2s2-toast"
      role={kind === "error" ? "alert" : "status"}
      data-kind={kind}
    >
      <div className="toast-body">{children}</div>
      <button className="toast-close" onClick={onDismiss} aria-label="Dismiss">
        ×
      </button>
    </div>
  );
}

// packages/ng-lib/src/lib/components/toast/toast.component.ts
import { Component, computed, input, output } from "@angular/core";
import { ToastKind } from "../../models/toast/toast.model";

@Component({
  selector: "m2s2-toast",
  templateUrl: "./toast.component.html",
  styleUrls: ["./toast.component.scss"],
  standalone: true,
  host: {
    "[attr.role]": "role()",
    "[attr.data-kind]": "kind()",
  },
})
export class ToastComponent {
  kind = input<ToastKind>("info");
  dismiss = output<void>();

  // Errors are assertive (announced immediately, interrupting); info/success
  // are polite (announced when the screen reader is next idle) — matches
  // each kind's actual urgency instead of one role for every toast.
  role = computed(() => (this.kind() === "error" ? "alert" : "status"));
}

<div class="toast-body">
  <ng-content />
</div>
<button class="toast-close" (click)="dismiss.emit()" aria-label="Dismiss">×</button>
